### ISSUE TITLE
Duplicate check failed: Error: File [{{folder name}}] not found, or is locked. If file exists, Please try again later

### ISSUE THREAD

**Issue by themmak13** [thesamim/TickTickSync#103]
**Describe the bug**
Once I started using TickTicksync I started getting this error multiple times a day and it does not stop appearing. 

Duplicate check failed: Error: File [{{folder name}}] not found, or is locked. If file exists, Please try again later

**To Reproduce**
Nothing has been done, but it is worth noting that every time I changed the name of the folder, error started appearing for another folder. Folders were: [Software/Obsidian], [Car], [Piano] & [Events]. 

**Screenshots**
![image](https://github.com/thesamim/TickTickSync/assets/68853379/f25b5b61-d5f5-41a8-bddf-c49adebf936c)
![image](https://github.com/thesamim/TickTickSync/assets/68853379/83d1883e-daa3-4635-b809-e58ede4ab966)
![image](https://github.com/thesamim/TickTickSync/assets/68853379/4f5627d6-1b0a-466d-8e70-7272a6c97633)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser no browser is used. but main browser in device is edge
 - Obsidian 1.5.12
 - Latest plugin update

**Comment by jee-ee** [comment]
This has been fixed for me in TickTickSync v1.0.22 as part of https://github.com/thesamim/TickTickSync/issues/99. Are you on the latest version?

**Comment by themmak13** [comment]
> This has been fixed for me in TickTickSync v1.0.22 as part of #99. Are you on the latest version?

@jee-ee  thank you for mentioning this, while I had v1.0.22 (just downloaded the plugin a couple of days ago) and the issue was persistent, apparently it was actually solved in a very recent version (v1.0.23). Thank you for highlighting looking at latest update.

**Comment by themmak13** [comment]
> This has been fixed for me in TickTickSync v1.0.22 as part of #99. Are you on the latest version?

@jee-ee   thank you for mentioning this, while I had v1.0.22 (just downloaded the plugin a couple of days ago) and the issue was persistent, apparently it was actually solved in a very recent version (v1.0.23). Thank you for highlighting looking at latest update.
