### ISSUE TITLE
Full vault sync causes #ticktick to be endlessly added to tasks

### ISSUE THREAD

**Issue by themmak13** [thesamim/TickTickSync#104]
**Describe the bug**
When "Full vault sync" is enabled and a new task is added anywhere in the vault , "#ticktick" is endlessly added to that task, I can sit and watch how a new tag is being typed and added every ~second. This is for tasks with no tag, if there was #ticktick tag this does not happen. 

I believe this has something to do with the plugin looping trying to establish the tag but it is appearing as normal text and the plugin keeps repeatedly adding "#ticktick" as a text, trying to establish the actual tag in order to stop looping.
![image](https://github.com/thesamim/TickTickSync/assets/68853379/c9e75790-c2f7-406d-85b9-275a6d643856)

**Screenshots**
![image](https://github.com/thesamim/TickTickSync/assets/68853379/cf9eb166-9a54-40fa-886c-af8ad0a5ebee)
![image](https://github.com/thesamim/TickTickSync/assets/68853379/62fc7870-7761-45dd-871f-a804d9fa0cb7)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Version Obsidian1.5.12

**Comment by thesamim** [comment]
Thanks for reporting. Will look into it.

**Comment by MassimoBaldrighi** [comment]
I have encounter the same issue, in my case I solved it by adding a space at the end of the task. IMO the system add the "#ticktick" tag but has no space before and so keep appending it at the end of the string until it's recognise as a real tag.

**Comment by thesamim** [comment]
@themmak13 , @MassimoBaldrighi :  I believe I've tested most scenarios of switching from No Full Vault Sync to Full Vault Sync and back. Please let me know if you find any issues.

Thanks.
