### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by masaoamano** [thesamim/TickTickSync#111]
When I enter my username and password and press login, I get a message 'login failed. undefined' and cannot log in. I can login TickTick with the same username (mail address) and password.

 - OS: MacOS14.4
 - Browser: Arc
 - Version 1.37

**Comment by thesamim** [comment]
Could you please turn on "Debug Mode" and [take a look at the console](https://forum.obsidian.md/t/opening-developer-console/66755/2) and let me know what you see?

**Comment by IMXeno123** [comment]
> > Could you please turn on "Debug Mode" and [take a look at the console](https://forum.obsidian.md/t/opening-developer-console/66755/2) and let me know what you see?
> 
> I ran into the exact same problem – can't log in and I get this 'login failed. undefined' message. I checked the console and there's no error messages there, but I've seen some really messed up error alerts on the device that's already logged in.
> 
> ```ts
> plugin:tickticksync:13168 {"baseUrl":"ticktick.com","token":"[154BB8FE91...] len: 336"}
> plugin:tickticksync:13208 Logged In: true
> plugin:tickticksync:23214 TickTickSync 1.0.25 loaded!
> plugin:tickticksync:13419 Error get all Tasks Error: No Results.
>     at TickTickRestAPI.getAllTasks (plugin:tickticksync:13415:15)
>     at async SyncMan.syncTickTickToObsidian (plugin:tickticksync:22783:28)
>     at async TickTickSync.scheduledSynchronization (plugin:tickticksync:23429:24)
>     at async HTMLDivElement.eval (plugin:tickticksync:23051:9)
> getAllTasks @ plugin:tickticksync:13419
> await in getAllTasks (async)
> syncTickTickToObsidian @ plugin:tickticksync:22783
> await in syncTickTickToObsidian (async)
> scheduledSynchronization @ plugin:tickticksync:23429
> await in scheduledSynchronization (async)
> eval @ plugin:tickticksync:23051
> plugin:tickticksync:22896 An error occurred while synchronizing: TypeError: Cannot read properties of undefined (reading 'length')
>     at SyncMan.syncTickTickToObsidian (plugin:tickticksync:22811:51)
>     at async TickTickSync.scheduledSynchronization (plugin:tickticksync:23429:24)
>     at async HTMLDivElement.eval (plugin:tickticksync:23051:9)
> syncTickTickToObsidian @ plugin:tickticksync:22896
> await in syncTickTickToObsidian (async)
> scheduledSynchronization @ plugin:tickticksync:23429
> await in scheduledSynchronization (async)
> eval @ plugin:tickticksync:23051
> plugin:tickticksync:20356 Converting line to Object, could not find project Id:  [testing](obsidian://open?vault=me&file=00_Tasks.md)
> convertLineToTask @ plugin:tickticksync:20356
> await in convertLineToTask (async)
> lineModifiedTaskCheck @ plugin:tickticksync:22306
> fullTextModifiedTaskCheck @ plugin:tickticksync:22659
> await in fullTextModifiedTaskCheck (async)
> scheduledSynchronization @ plugin:tickticksync:23521
> await in scheduledSynchronization (async)
> eval @ plugin:tickticksync:23051
> plugin:tickticksync:20356 Converting line to Object, could not find project Id:  hi ticktick
> convertLineToTask @ plugin:tickticksync:20356
> await in convertLineToTask (async)
> lineModifiedTaskCheck @ plugin:tickticksync:22306
> fullTextModifiedTaskCheck @ plugin:tickticksync:22659
> await in fullTextModifiedTaskCheck (async)
> scheduledSynchronization @ plugin:tickticksync:23521
> await in scheduledSynchronization (async)
> eval @ plugin:tickticksync:23051
> ```

@thesamim Now these errors render the TickTickSync completely unusable and it is broken.

**Comment by thesamim** [comment]
Great. Happening for me too. Something's going on on the TickTick side. I've got three other crises on my plate right now. Will get back to you ASAP.

**Comment by thesamim** [comment]
TickTick has once again changed checkpoint processing.  Checking in Fix shortly.
