### ISSUE TITLE
Overdue task - check in TickTick not updating in Obsidian

### ISSUE THREAD

**Issue by ms3056** [thesamim/TickTickSync#112]
**Describe the bug**
I have tasks successfully created in Obsidian sync'd to TickTick. I have the limit sync set to use the obs tag, and the tasks have this tag. I then check them in TickTick - even with the Obsidian file the task lives on open - and nothing happens in Obsidian and disappears from TickTick.  I then Check Database and the task comes back to TickTick. 

**Expected behavior**
Check a overdue task in TickTick and then have that task checked in Obsidian. 

Please note - the video cuts off before the task gets checked in TickTick after checking it in Obsidian - but - I want to check tasks in TickTick and have them checked in Obsidian,. 

https://github.com/thesamim/TickTickSync/assets/23712700/b8313fcd-1321-45a8-bf5c-d7e951f01f6b

**Comment by thesamim** [comment]
Some questions

1. What plugin is that in the sidebar?
2. If you check the task from a note, not from the plugin, does it work as expected?
3. When you check the task from the plugin, does the Tasks plugin recognize it as done?

**Comment by ms3056** [comment]
I think either I was not waiting long enough, or your recent fixes changed things - everything is working fine now. 

Thank you so much for this plugin.
