### ISSUE TITLE
login Failed.undifned

### ISSUE THREAD

**Issue by dwrinn** [thesamim/TickTickSync#113]
**Describe the bug**
Hi, when I try to login to my account, It's telling me both on my Ipad and my PC that the login failed.undfined. c
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by IMXeno123** [comment]
Please check this issue!  
#111 cannot login

**Comment by thesamim** [comment]
TickTick has once again changed checkpoint processing.  Checking in Fix shortly.
