### ISSUE TITLE
Completed tasks in TickTick is not syncing to obsidian

### ISSUE THREAD

**Issue by k-vasiliev** [thesamim/TickTickSync#116]
**Describe the bug**
When i mark task as complete in TickTick it is not marked as complete in obsidian

**To Reproduce**
1. Create task in TickTick
2. Run sync in Oblivion
3. Mark task as done
2. Run sync in Oblivion

**Expected behavior**
Task marked as done in both apps

**Desktop (please complete the following information):**
 - OS: MacOs
 - Chrome

**Smartphone (please complete the following information):**
is not used in this scenario

**Additional context**
I created new account in TickTick exactly to test sync behavior if this is relevant. Also i noticed some task duplicated (tasks that i only created and didnt change during this scenario)

**Comment by thesamim** [comment]
Does this happen for all tasks or only tasks in certain projects?
Does this happen for all tasks or tasks in certain notes?
Does marking the task done in Obsidian mark the task in TickTick?
The duplicates: Are they in notes that have default projects set?
Are you limiting the syncing by project or tag?
Do you have any other plugins, other than Tasks, that are related to task management?

**Comment by k-vasiliev** [comment]
> Does this happen for all tasks or only tasks in certain projects?
> Does this happen for all tasks or tasks in certain notes?

I tested for tasks that consists in the lists and for inbox tasks, they all not syncing 
Just tested this way - cleared all tasks from TickTick and removed notes from obsidian. Created new list and task inside it

> Does marking the task done in Obsidian mark the task in TickTick?

Yes

> Are you limiting the syncing by project or tag?

No, i did use default settings

> Do you have any other plugins, other than Tasks, that are related to task management?

I disabled all community plugins for the test. List of enabled core plugins:

* Backlinks
* Canvas
* Command palette
* Daily notes
* File recovery
* Page preview
* Quick switcher
* Templates

**Comment by thesamim** [comment]
Found the problem. Related to TickTick API change. Fixing.

Thanks for testing and reporting.

**Comment by thesamim** [comment]
@k-vasiliev : Could you please confirm that the problem is fixed in 1.0.27?

**Comment by k-vasiliev** [comment]
Can confirm, thank you for fast fix!
