### ISSUE TITLE
Add option to move project md files to a different folder

### ISSUE THREAD

**Issue by sdelcore** [thesamim/TickTickSync#12]
Thanks for the great work and looking forward to using it. I would find it useful if we could select a folder to sync the lists to.

For example. Currently the plugins generate the .md files in the root of the vault. But I would like to have them moved to a `tasks/` or a `ticktick/` folder.

**Comment by thesamim** [comment]
Would it be useful to have the folder structure follow the folder structure in TickTick?

**Comment by sdelcore** [comment]
Yeah I think that would help keep it clean. But at the very least there should be an option to define the root folder in the vault for  the lists
