### ISSUE TITLE
Login Failed "Get Inbox Properties" 

### ISSUE THREAD

**Issue by ajvalenc** [thesamim/TickTickSync#120]
**Describe the bug**
I am getting the following error when trying to login (I was able to login before). It's happening in all my devices (MacOS and iOS). 

Edit: I tried creating a new account on TickTick and set up an empty vault on Obsidian with just this plugin and I get the same error.

**Screenshots**
<img width="239" alt="Screenshot 2024-04-16 at 2 36 06 PM" src="https://github.com/thesamim/TickTickSync/assets/26698897/474e3f04-f530-4dcd-b470-530f82651b4c">

**Comment by ms3056** [comment]
I am having the same issue.

**Comment by ms3056** [comment]
> @ms3056, @ajvalenc : Just to confirm you are able to login and all is working now?
> 
> If so: TickTick may have been doing some maintenance at the time... If not: Please let me know.

Everything is fine. Honestly - I think I got the plugin or my use of it into a weird state. 

1. I was using the plugin fine, but I noticed that tasks created in TickTick were not coming into Obsidian - I did many tweaks, and I hit the "sync" button and the check databases buttons A LOT
2. I then uninstalled the plugin, restarted Obsidian, re-installed
3. When tried to enter my login credentials I got the error. 

I think I overloaded the API with too many calls in a short time? Maybe? 

And in the end - the problem with tasks coming to Obsidian from TickTick was USER ERROR - I didn't have the configuration correct - so it was my fault. 

In the end - everything is working fine in both directions for me. I only elaborated in case you recognize something and it helps you in the future.

**Comment by thesamim** [comment]
> I think I overloaded the API with too many calls in a short time? Maybe?

I really don't think you did anything wrong. I think TickTick was doing maintenance at the time.

I appreciate the detailed update. Thank you.

**Comment by thesamim** [comment]
TickTick system issue...

**Comment by dem0ngo** [comment]
I'm having the same issue and I've tried both yesterday and today.

**Comment by thesamim** [comment]
> I'm having the same issue and I've tried both yesterday and today.

I will be tracking this in https://github.com/thesamim/TickTickSync/issues/120

**Comment by thesamim** [comment]
All: Will be digging into this. 

If you could please: turn on Debug Mode and past logs of what you see, here. Thanks.
