### ISSUE TITLE
Ticktick is not syncing from tick tick to obsidian

### ISSUE THREAD

**Issue by Suyashtnt** [thesamim/TickTickSync#122]
**Describe the bug**
Whenever I click the  `sync` button in settings, obsidian just doesn't sync from ticktick. It seems to not be able to fetch tasks put to only push tasks

**To Reproduce**
1. Login
2. Click sync (assuming there are already tasks in obisidan that need to be synced)
3. Edit task in tick tick
4. Resync
5. The task on obsidian doesn't sync. It only pushed the original back to tick tick.

**Expected behavior**
The updated task in tick tick to override the one in obsidian

**Screenshots**
Console Log during sync:
![image](https://github.com/thesamim/TickTickSync/assets/45307955/1d804a9f-838b-4754-b21d-86001c3168a1)

**Desktop (please complete the following information):**
 - OS: NixOS
 - Browser: N/A
 - Version: NixOs Nightly, Obsidian 1.5.12

**Additional context**
This only started happening recently. Not sure which version started causing it

**Comment by thesamim** [comment]
Please see: https://github.com/thesamim/TickTickSync/issues/125 
Are you seeing the same thing?

**Comment by Suyashtnt** [comment]
> Please see: #125 Are you seeing the same thing?

yes

**Comment by thesamim** [comment]
Please try with 1.0.28

**Comment by thesamim** [comment]
Closing this and tracking with https://github.com/thesamim/TickTickSync/issues/125

Please let me know your findings.
