### ISSUE TITLE
Checkpoint Fetch failing

### ISSUE THREAD

**Issue by blakebenton** [thesamim/TickTickSync#125]
Initial authentication with the plugin to TickTick account fails.  Error popup is "Login Failed.undefined"

1. Go to plugin settings 
2. Enter TickTick Username and Password
3. Click the Login button.
4. Get following error:
![image](https://github.com/thesamim/TickTickSync/assets/18176052/b47eb726-37e3-4434-a666-3abfc100ff29)

After pulling up the developer console I can see that I actually do get signed in, and get a token.  I get a series of "Check point has been changed." messages and then it bails out.
![image](https://github.com/thesamim/TickTickSync/assets/18176052/c3f6c3ba-7451-4782-ae4f-c3737897a9eb)

Environment
 - MacOS - 14.4.1
 - Obsidian Version - 1.5.12
 - Plugin Version - 1.0.27

**Comment by viviengarcia** [comment]
Same here (issue, os, versions) 😅

**Comment by thesamim** [comment]
Looks like TickTick has made another change... Will investigate ASAP.

**Comment by thesamim** [comment]
Please try with 1.0.28

**Comment by thesamim** [comment]
Ok, this at least fetches the tasks. But I'm not convinced everything is back to normal. Will test some more tomorrow.

**Comment by viviengarcia** [comment]
Still get the error with v1.0.28

**Comment by thesamim** [comment]
Could you paste your console log please?

**Comment by Suyashtnt** [comment]
![image](https://github.com/thesamim/TickTickSync/assets/45307955/89676655-5810-4084-a989-bbb7af22303d)

I have the same issue still. Heres my logs

**Comment by viviengarcia** [comment]
![Screenshot 2024-04-24 at 09 42 56](https://github.com/thesamim/TickTickSync/assets/1825862/cc91c56c-b14e-4e09-9daa-a8e71f77c0ed)

**Comment by viviengarcia** [comment]
![Screenshot 2024-04-24 at 09 42 56](https://github.com/thesamim/TickTickSync/assets/1825862/b96376e0-7fa5-43c7-ad48-6190c415125b)

**Comment by thesamim** [comment]
Thanks. Working on it now.

**Comment by thesamim** [comment]
Please try again with release 1.0.29.

If you still encounter issues:
1. make sure Debug Mode is turned on
2. right-click in the console log and choose "Save As"
3. Send me the whole log please.

What's going on:
When fetching tasks from TickTick, one of the parameters is a "checkpoint".
What I have learned through experimentation is that "checkpoint" is actually an epoch time from the last fetch. So, theoretically Ticktick is only returning changes since the last checkpoint.
When I first wrote the plugin, Ticktick accepted 0 as a valid checkpoint, and returned all tasks.
Then it didn't
Then -1 returned returned all tasks.
Then it didn't. (Full disclosure: running from postman, it still did. But not from the plugin. I haven't quite figured that one out.)
So now I'm attempting to set the starting checkpoint as 2013-01-01T00:00:00.000+0000, which is the year that TickTick started. 
This has worked on my vault.
I'm hoping it works for all vaults.

In the fullness of time, I want to update the fetch logic in TickTickSync to take advantage of this "feature" and reduce the network traffic. As in: Determine an arbitrary starting point for fetching (eg: 2013-01-01T00:00:00.000+0000), then keep track of the last fetch date and process task changes accordingly. I'm sure there will be some unwanted side-effects so I want to thoroughly test the theory before releasing it.

**Comment by Suyashtnt** [comment]
> Please try again with release 1.0.29.
> 
> If you still encounter issues:
> 
>     1. make sure Debug Mode is turned on
> 
>     2. right-click in the console log and choose "Save As"
> 
>     3. Send me the whole log please.
> 
> 
> What's going on: When fetching tasks from TickTick, one of the parameters is a "checkpoint". What I have learned through experimentation is that "checkpoint" is actually an epoch time from the last fetch. So, theoretically Ticktick is only returning changes since the last checkpoint. When I first wrote the plugin, Ticktick accepted 0 as a valid checkpoint, and returned all tasks. Then it didn't Then -1 returned returned all tasks. Then it didn't. (Full disclosure: running from postman, it still did. But not from the plugin. I haven't quite figured that one out.) So now I'm attempting to set the starting checkpoint as 2013-01-01T00:00:00.000+0000, which is the year that TickTick started. This has worked on my vault. I'm hoping it works for all vaults.
> 
> In the fullness of time, I want to update the fetch logic in TickTickSync to take advantage of this "feature" and reduce the network traffic. As in: Determine an arbitrary starting point for fetching (eg: 2013-01-01T00:00:00.000+0000), then keep track of the last fetch date and process task changes accordingly. I'm sure there will be some unwanted side-effects so I want to thoroughly test the theory before releasing it.

[log.log](https://github.com/thesamim/TickTickSync/files/15098799/log.log)
looks like it still aint working

**Comment by thesamim** [comment]
> looks like it still aint working

Need more info, please:
1. Close all instances of Obsidian
2. Reopen the one vault with TickTickSyn enabled
3. Login from settings
4. Do a Sync
5. Send logs again please.

Please do NOT do a "Check Database.", it's just adding unnecessary logging at this point.

Thanks

**Comment by viviengarcia** [comment]
Doesn't work for me neither. TickTickSync 1.0.29, applied the instructions above, can't even login: `Login Failed.undefined`.
```LogTalk
23:40:22.724 plugin:tickticksync:12250 Starting Checkpoint date:  Tue Jan 01 2013 01:00:00 GMT+0100 (Central European Standard Time) Checkpoint 1356998400000
23:40:23.261 plugin:tickticksync:12270 Signed in Response:  Object
23:40:23.494 plugin:tickticksync:12748 Date:  Mon Dec 17 2012 01:00:00 GMT+0100 (Central European Standard Time)
23:40:23.495 plugin:tickticksync:12750 Date:  Mon Dec 17 2012 01:00:00 GMT+0100 (Central European Standard Time)
23:40:23.495 plugin:tickticksync:12751 Attempted Checkpoint:  1355702400000
23:40:23.495 plugin:tickticksync:12753 Check point has been changed. 1355702400000
getNextCheckPoint @ plugin:tickticksync:12753
getInboxProperties @ plugin:tickticksync:12305
23:40:23.677 plugin:tickticksync:12748 Date:  Sun Dec 02 2012 01:00:00 GMT+0100 (Central European Standard Time)
23:40:23.678 plugin:tickticksync:12750 Date:  Sun Dec 02 2012 01:00:00 GMT+0100 (Central European Standard Time)
23:40:23.678 plugin:tickticksync:12751 Attempted Checkpoint:  1354406400000
23:40:23.678 plugin:tickticksync:12753 Check point has been changed. 1354406400000
getNextCheckPoint @ plugin:tickticksync:12753
getInboxProperties @ plugin:tickticksync:12305
23:40:23.855 plugin:tickticksync:12748 Date:  Sat Nov 17 2012 01:00:00 GMT+0100 (Central European Standard Time)
23:40:23.855 plugin:tickticksync:12750 Date:  Sat Nov 17 2012 01:00:00 GMT+0100 (Central European Standard Time)
23:40:23.855 plugin:tickticksync:12751 Attempted Checkpoint:  1353110400000
23:40:23.855 plugin:tickticksync:12753 Check point has been changed. 1353110400000
getNextCheckPoint @ plugin:tickticksync:12753
getInboxProperties @ plugin:tickticksync:12305
23:40:24.050 plugin:tickticksync:12748 Date:  Fri Nov 02 2012 01:00:00 GMT+0100 (Central European Standard Time)
23:40:24.050 plugin:tickticksync:12750 Date:  Fri Nov 02 2012 01:00:00 GMT+0100 (Central European Standard Time)
23:40:24.051 plugin:tickticksync:12751 Attempted Checkpoint:  1351814400000
23:40:24.051 plugin:tickticksync:12753 Check point has been changed. 1351814400000
getNextCheckPoint @ plugin:tickticksync:12753
getInboxProperties @ plugin:tickticksync:12305
23:40:24.230 plugin:tickticksync:12748 Date:  Thu Oct 18 2012 01:00:00 GMT+0200 (Central European Summer Time)
23:40:24.230 plugin:tickticksync:12750 Date:  Thu Oct 18 2012 01:00:00 GMT+0200 (Central European Summer Time)
23:40:24.230 plugin:tickticksync:12751 Attempted Checkpoint:  1350514800000
23:40:24.231 plugin:tickticksync:12753 Check point has been changed. 1350514800000
getNextCheckPoint @ plugin:tickticksync:12753
getInboxProperties @ plugin:tickticksync:12305
23:40:24.408 plugin:tickticksync:12748 Date:  Wed Oct 03 2012 01:00:00 GMT+0200 (Central European Summer Time)
23:40:24.408 plugin:tickticksync:12750 Date:  Wed Oct 03 2012 01:00:00 GMT+0200 (Central European Summer Time)
23:40:24.409 plugin:tickticksync:12751 Attempted Checkpoint:  1349218800000
23:40:24.409 plugin:tickticksync:12753 Check point has been changed. 1349218800000
getNextCheckPoint @ plugin:tickticksync:12753
getInboxProperties @ plugin:tickticksync:12305
23:40:24.600 plugin:tickticksync:12748 Date:  Tue Sep 18 2012 01:00:00 GMT+0200 (Central European Summer Time)
23:40:24.601 plugin:tickticksync:12750 Date:  Tue Sep 18 2012 01:00:00 GMT+0200 (Central European Summer Time)
23:40:24.601 plugin:tickticksync:12751 Attempted Checkpoint:  1347922800000
23:40:24.601 plugin:tickticksync:12753 Check point has been changed. 1347922800000
getNextCheckPoint @ plugin:tickticksync:12753
getInboxProperties @ plugin:tickticksync:12305
23:40:24.782 plugin:tickticksync:12748 Date:  Mon Sep 03 2012 01:00:00 GMT+0200 (Central European Summer Time)
23:40:24.783 plugin:tickticksync:12750 Date:  Mon Sep 03 2012 01:00:00 GMT+0200 (Central European Summer Time)
23:40:24.783 plugin:tickticksync:12751 Attempted Checkpoint:  1346626800000
23:40:24.783 plugin:tickticksync:12753 Check point has been changed. 1346626800000
getNextCheckPoint @ plugin:tickticksync:12753
getInboxProperties @ plugin:tickticksync:12305
23:40:25.000 plugin:tickticksync:12748 Date:  Sun Aug 19 2012 01:00:00 GMT+0200 (Central European Summer Time)
23:40:25.001 plugin:tickticksync:12750 Date:  Sun Aug 19 2012 01:00:00 GMT+0200 (Central European Summer Time)
23:40:25.001 plugin:tickticksync:12751 Attempted Checkpoint:  1345330800000
23:40:25.001 plugin:tickticksync:12753 Check point has been changed. 1345330800000
getNextCheckPoint @ plugin:tickticksync:12753
getInboxProperties @ plugin:tickticksync:12305
23:40:25.203 plugin:tickticksync:12748 Date:  Sat Aug 04 2012 01:00:00 GMT+0200 (Central European Summer Time)
23:40:25.204 plugin:tickticksync:12750 Date:  Sat Aug 04 2012 01:00:00 GMT+0200 (Central European Summer Time)
23:40:25.204 plugin:tickticksync:12751 Attempted Checkpoint:  1344034800000
23:40:25.204 plugin:tickticksync:12753 Check point has been changed. 1344034800000
getNextCheckPoint @ plugin:tickticksync:12753
getInboxProperties @ plugin:tickticksync:12305
```

**Comment by thesamim** [comment]
@viviengarcia : could you please show me the log after you click on Sync?

**Comment by Suyashtnt** [comment]
> > looks like it still aint working
> 
> Need more info, please:
> 
>     1. Close all instances of Obsidian
> 
>     2. Reopen the one vault with TickTickSyn enabled
> 
>     3. Login from settings
> 
>     4. Do a Sync
> 
>     5. Send logs again please.
> 
> 
> Please do NOT do a "Check Database.", it's just adding unnecessary logging at this point.
> 
> Thanks

Uh it seems to have all of a sudden started working on my laptop, Weird. Logs seem good now as well

**Comment by viviengarcia** [comment]
@thesamim I don't have the Sync button, since the login fails

**Comment by thesamim** [comment]
> @thesamim I don't have the Sync button, since the login fails

If you turn on debug mode, you will see a sync button in your icons bar. You may have to close obsidian and open it again. 

Also if you close settings and open it again. 

Q: when's the last time you had a successful login.

**Comment by thesamim** [comment]
> Uh it seems to have all of a sudden started working on my laptop, Weird. Logs seem good now as well

Mixed blessings: on the one hand, great it's working! 

On the other hand, but we still don't know what the differences between your set up and mine (that resulted in stuff working for me but not for you) were. 

As a software engineer: "it suddenly started working again"  is just as scary as "it suddenly stopped working." It means the problem is going to come back at some point. 

Of course, part of this is that we are the mercy of ticktick and the undocumented API. But that's a different discussion.

**Comment by thesamim** [comment]
@viviengarcia, @blakebenton , @Suyashtnt : I'm leaving this issue open until I'm convinced that we're back to steady state.

**Comment by viviengarcia** [comment]
I already had debug mode turned on (at least in tickticksync). I tried turning both obsidian and your plugin off and on again but no sync button. Also I just started with ticktick so I never could login from tickticksync (no issue using ticktick app or web though)

25 Apr 2024 16:28:23 thesamim ***@***.***>:

**Comment by blakebenton** [comment]
I'm still seeing the same issue.  I never get logged in, when I hit the sync button on the toolbar it does nothing because it never was logged in, no messages in console or anything.

**Comment by thesamim** [comment]
> I'm still seeing the same issue. I never get logged in, when I hit the sync button on the toolbar it does nothing because it never was logged in, no messages in console or anything.

Questions:
1. Have you ever been able to login with TickTickSync?
2. When you login to TickTick, on the Web or on the App, are you using an email and password combination or are you using Google/Apple/Facebook? If you are using one of those authenticators, are you able to sign in with email/password only?
3. Do you have Debug Mode turned on in the settings?

**Comment by blakebenton** [comment]
Thank you for your response.
1. No I've never logged in, first time I've attempted to use TickTickSync
2. I'm logging in with email/password combo, NOT  using Google/Apple/Facebook. 
3. I have Debug Mode turned on in the TickTickSync settings

**Comment by viviengarcia** [comment]
> Highlighted is the Sync Button. If you don't see that, we're dealing with a different issue altogether.

Thanks I missed that.

> When you login to TickTick, on the Web or on the App, are you using an email and password combination or are you using Google/Apple/Facebook? If you are using one of those authenticators, are you able to sign in with email/password only?

I'm using email & password combination from the start to login in the app and on the web.

> If you can send me the console log from your attempt to login, I will try to figure out what's going on.

There. Edited personal info (user id, user code, email).
What I did : 

1. Cleared console log
2. Deactivated TickTickSync
3. Restarted obsidian
4. Activated TicktickSync
5. Initiated login from settings
6. > "Login Failed.undefined"
7. Clicked on the sync button
8. > "Please login from the settings"
9. > "Sync completed" (no)
10. Opened console and exported the log

[obsidian.md-1714090845735.log](https://github.com/thesamim/TickTickSync/files/15123557/obsidian.md-1714090845735.log)

**Comment by thesamim** [comment]
@viviengarcia , @blakebenton : The datapoint I was missing was this was the first time y'all were loging in. This in addition to a change on the TickTick side was the root cause.

Please try again with 1.0.30

Thanks for your patience.

**Comment by viviengarcia** [comment]
Thanks a lot @thesamim, I tried earlier on my phone and it worked! … Unfortunately I got this message on desktop app (the main device I tried to make TickTickSync work):

<img src="https://github.com/thesamim/TickTickSync/assets/1825862/ed8f0b49-0d08-4992-a059-704a84de5435" width=40% height=40%>

I did a bit of research to see if I could follow some instructions to resolve the issue by myself, with no success so far.

**Comment by thesamim** [comment]
@viviengarcia : Glad it's at least working on the phone.

that's the error ticktick spits back when you get the email or password wrong. But sometimes it throws that up when it's confused. If you are able to login with that userid and password on the web, but not on the application, chances are I'm still missing something in the code. 

Question: Are you sure you are on 1.0.30 on your desktop? I fixed this 
![image](https://github.com/thesamim/TickTickSync/assets/5315625/5c2044d3-44cf-4d02-b956-25f3d809ff84)
 to give an actual error message in 1.0.30.

**Comment by viviengarcia** [comment]
Yes, the `Login Failed.undefined` was probably from before I updated the plugin. I restarted obsidian to be sure, tried to login and got this:

<img src="https://github.com/thesamim/TickTickSync/assets/1825862/20901756-c48b-4780-88eb-b51574a63c93" width=40% height=40%>

Here is the log: 
[obsidian.md-1714164905651.log](https://github.com/thesamim/TickTickSync/files/15135219/obsidian.md-1714164905651.log)

**Comment by thesamim** [comment]
> Yes, the `Login Failed.undefined` was probably from before I updated the plugin. I restarted obsidian to be sure, [...]

Great.

When you log in from the Web right now, are you able to login?

If you are not: you will probably need to either wait 24 hours or ask ticktick for a reset via their support email.

This: 
`22:50:30.560 plugin:tickticksync:12777 {"baseUrl":"ticktick.com","token":"[0CAB80045A...] len: 368"}`
tells me you had at least one successful login at some point from TickTickSync

Question: Are you using the same vault on both your desktop and your phone?
If so: are you using the same userid and password on both?

**Comment by viviengarcia** [comment]
> When you log in from the Web right now, are you able to login?
Yes
 
> If you are not: you will probably need to either wait 24 hours or ask ticktick for a reset via their support email.
Noted, I'll stop login on desktop for now and try in 24H
 
> This: `22:50:30.560 plugin:tickticksync:12777 {"baseUrl":"ticktick.com","token":"[0CAB80045A...] len: 368"}` tells me you had at least one successful login at some point from TickTickSync
You mean on desktop?

> Question: Are you using the same vault on both your desktop and your phone? If so: are you using the same userid and password on both? 
Yes, same vault and same userid/pswd on every device (obsidian, vault, ticktick)

**Comment by thesamim** [comment]
> > When you log in from the Web right now, are you able to login?> 
> > > Yes

That tells me there's an issue with the way the login is being processed from the desktop. 

> You mean on desktop?
> 
Now that I know you are using the same vault on both dekstop and phone, it may be a result of the successful login on the phone.

How are you synchronizing between desktop and phone?

Out of curiosity: What happens if you just try clicking on "Sync"?

The next troubleshooting steps are:

1. uninstall TickTickSync on desktop
2. disable all other plugins on dekstop (for now)
3. re-install TickTickSyn on desktop
4. Try to login
5. If  it works: re-enable other plugins and try clicking on "Sync". Let met know what happens. Then we enable other plugins one by one and see if any of them interfere....
6. If it doesn't work: Could you please send me your data.json file from the TickTickSync plugin directory. (Please edit any sensitive information in data.json....)

**Comment by blakebenton** [comment]
Working for me now!  Thank you!

**Comment by thesamim** [comment]
@viviengarcia @blakebenton @Suyashtnt :
Thank you for your help.
