### ISSUE TITLE
Support dida

### ISSUE THREAD

**Issue by quanru** [thesamim/TickTickSync#13]
ticktick has a china version which official site is https://dida365.com/, and its base url is https://api.dida365.com/

https://github.com/lucasvtiradentes/ticktick-api-lvt/pull/10

**Comment by thesamim** [comment]
Have you looked at: https://obsidian.md/plugins?id=dida-sync ?

**Comment by thesamim** [comment]
@quanru : Could you please confirm if you are able to login with the API today? Thanks.

**Comment by quanru** [comment]
yeah, i can login with the api today:

![image](https://github.com/thesamim/TickTickSync/assets/11739753/c10916f7-41d0-458b-92dc-cd2abe207b82)
![image](https://github.com/thesamim/TickTickSync/assets/11739753/c10916f7-41d0-458b-92dc-cd2abe207b82)
![image](https://github.com/thesamim/TickTickSync/assets/11739753/a594d6a6-a024-4c95-89fd-18c7aceef3cc)

**Comment by thesamim** [comment]
> yeah, i can login with the api today:

Thanks. Is that on ticktick.com or dida.com?

**Comment by quanru** [comment]
dida.com

**Comment by thesamim** [comment]
@quanru : Could you please test on branch: [13-support-dida](https://github.com/thesamim/TickTickSync/tree/13-support-dida)

I don't have a Dida account...

**Comment by quanru** [comment]
> @quanru : Could you please test on branch: [13-support-dida](https://github.com/thesamim/TickTickSync/tree/13-support-dida)
> 
> I don't have a Dida account...

I'd love to

**Comment by anschein** [comment]
After testing on the branch, I entered the account password and successfully logged in on the login page, but the task could not be synchronized. The upper right corner prompted Please set the ticktick api first, and an error was thrown in developer mode.
![image](https://github.com/thesamim/TickTickSync/assets/49552476/fb198d36-17aa-4e70-9c4d-a449ce1b7c4a)

**Comment by thesamim** [comment]
@anschein 
If you are comfortable doing so:

1.  Please go to `<root of your vault>\.obsidian\plugins\tickticksync\`
2. make a copy of main.js
3. extract the attached main.js and copy it to `<root of your vault>\.obsidian\plugins\tickticksync\`
4. Try loging in again.

This has better debugging output. It might give me a clue what's going on.

Please ignore the drop down for choosing a server. I have only tested with ticktick.com (which I believe is what you are using anyway...)

[main.zip](https://github.com/thesamim/TickTickSync/files/13880749/main.zip)

**Comment by anschein** [comment]
Use this main.js
If nothing is selected in the drop-down menu
![image](https://github.com/thesamim/TickTickSync/assets/49552476/227d81dc-658a-41b4-a3f5-dc1c03a906bd)
If selected dida,There is no output from the console,and the upper right corner prompted Please set the ticktick api first
And switch to ticktick same result

**Comment by anschein** [comment]
> @anschein If you are comfortable doing so:
> 
> 1. Please go to `<root of your vault>\.obsidian\plugins\tickticksync\`
> 2. make a copy of main.js
> 3. extract the attached main.js and copy it to `<root of your vault>\.obsidian\plugins\tickticksync\`
> 4. Try loging in again.
> 
> This has better debugging output. It might give me a clue what's going on.
> 
> Please ignore the drop down for choosing a server. I have only tested with ticktick.com (which I believe is what you are using anyway...)
> 
> [main.zip](https://github.com/thesamim/TickTickSync/files/13880749/main.zip)

I'm trying to use dida,looks like didn't have any luck

**Comment by quanru** [comment]
@thesamim I have signed up for a dida account that can be tested for you to use:

account: quanruzhuoxiu@qq.com
passwd：123456789

**Comment by thesamim** [comment]
@quanru, @anschein : Thanks for testing with this. I think I know what I did wrong and am working on fixing it now. Will update as soon as possible.

**Comment by thesamim** [comment]
@quanru , @anschein : I think I found the problems (there were several. :( )

Could I ask you to please test with the attached? Extract all three files to a plugin folder....

There might still be issues, so please take backups if you're dealing with live tasks.

Thanks!


[tickticksynct1.1.10-test.zip](https://github.com/thesamim/TickTickSync/files/13929183/tickticksynct1.1.10-test.zip)

**Comment by anschein** [comment]
> @quanru,@anschein：我想我发现了问题（有几个。:( ）
> 
> 我可以请你用附件测试一下吗？将所有三个文件解压到插件文件夹中......
> 
> 可能仍然存在问题，因此如果您正在处理实时任务，请进行备份。
> 
> 谢谢！
> 
> [tickticsynct1.1.10-test.zip](https://github.com/thesamim/TickTickSync/files/13929183/tickticksynct1.1.10-test.zip)

The new plugin handles synchronization normally and works like magic!
Is it currently impossible to use the tasks plugin to query dates?

**Comment by anschein** [comment]
I found that my tags in dida were corrupted during the sync process, unfortunately I forgot to back it up and when I restored the tags I tried syncing again

**Comment by anschein** [comment]
![image](https://github.com/thesamim/TickTickSync/assets/49552476/4b5ed8b1-d33e-49b6-973a-bf4efbcb7d11)
This error occurred when I tried to create a folder to put all synchronized tasks in one folder. If I choose root directory synchronization, there will be no problem.

**Comment by anschein** [comment]
> ![image](https://private-user-images.githubusercontent.com/49552476/296530058-4b5ed8b1-d33e-49b6-973a-bf4efbcb7d11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMDczMDcsIm5iZiI6MTcwNTIwNzAwNywicGF0aCI6Ii80OTU1MjQ3Ni8yOTY1MzAwNTgtNGI1ZWQ4YjEtZDMzZS00OWI2LTk3M2EtYmY0ZWZiY2I3ZDExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDA0MzY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyNTI2ZWRiYTNjODJjY2E4NDE0Y2VhMjZmNzFlMzk2YWZjYWMzNmNhOGIzZmQyMjk5NDY4MGQ1Yjc3ZThiOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.actMcEKGnOg8KRbzxNwGFje7mv0R_YUlwJlKZFV1w_4) This error occurred when I tried to create a folder to put all synchronized tasks in one folder. If I choose root directory synchronization, there will be no problem.

If I delete the destination folder and use the plug-in to create a new folder, what will happen is that the destination folder is created and synchronization stops after synchronizing an md file.
![image](https://github.com/thesamim/TickTickSync/assets/49552476/82b60d19-a14b-4fea-bd13-822fa2269d6d)

**Comment by thesamim** [comment]
@anschein 
> I found that my tags in dida were corrupted during the sync process,  

Could you please create those tags in the account that @quanru created? I suspect that the issue may be Chinese characters that I'm not capturing correctly.

**Comment by thesamim** [comment]
> > @quanru
> [...] Is it currently impossible to use the tasks plugin to query dates?

Currently: Yes. I plan to fix that in 1.1.11 (release after next.)

**Comment by thesamim** [comment]
@anschein : re: Folder issues.

Could you please paste here your folder name and your md file name?

**Comment by anschein** [comment]
> @anschein : re: Folder issues.
> 
> Could you please paste here your folder name and your md file name?

I made a mistake, I used '/dida' instead of dida

**Comment by anschein** [comment]
> @anschein
> 
> > I found that my tags in dida were corrupted during the sync process,
> 
> Could you please create those tags in the account that @quanru created? I suspect that the issue may be Chinese characters that I'm not capturing correctly.

I used a test account for synchronization. When I added a link-based task in dida and started synchronization, the `rd` tag was automatically added to dida after the synchronization was completed. When I used my own account to synchronize, it also Many tags similar to `wechat` or other garbled characters have been added, but these tags do not appear in obsidian after synchronization. You can see the tasks I used in the test account.
![image](https://github.com/thesamim/TickTickSync/assets/49552476/1ef07fd9-cab7-47c9-9395-aeda557e4f79)

By the way, is it true that any form of task movement is not supported? I tried to create a new task in dida's inbox and synchronized it to obsidian. When I moved the task to the test list in dida and synchronized it again in obsidian, the task was automatically deleted in both dida and obsidian.

**Comment by thesamim** [comment]
> I made a mistake, I used '/dida' instead of dida

Added code to verify that created folder is valid before updating settings.

**Comment by thesamim** [comment]
> By the way, is it true that any form of task movement is not supported?

As of right now: Yes. That's going to be a heavy lift. I'm thinking it is a needed function though, so I will implement in the fullness of time.

**Comment by thesamim** [comment]
@quanru , @anschein : I believe I found the bugs. There were two: 

1. Not accounting for default folder in all parts of the app.
2. Incorrect RegEx for Tag Handling. Which, incidentally, did not account for non-latin languages.

I **believe** I have fixed both issues. 

May I ask you to test again please? There's a whole bunch of extra logging in case we run into more issues. Again: This is still very much test code.

Thank you!

[tickticksync1.1.10 - Test 2.zip](https://github.com/thesamim/TickTickSync/files/13943462/tickticksync1.1.10.-.Test.2.zip)
