### ISSUE TITLE
Minor Issue: message whenever I edit ANY task

### ISSUE THREAD

**Issue by ms3056** [thesamim/TickTickSync#134]
I have tasks that I do not sync with TickTick. These tasks contain no tags. When I check or uncheck them I get a message in Obsidian in the upper right corner. Nothing else seems to happen - I don't see these tasks in TickTick (which is good) but I was wondering if you could consider not showing the message for tasks that are not synced? 

Example task:
`- [ ] 12:00-13:00 **Executive Talks** [Notes](Journal/Notes/2024-May/20240524103940) 📍Desk`

![image](https://github.com/thesamim/TickTickSync/assets/23712700/3386ddcc-16bc-45dc-8e92-6a3a02f20a71)

**Comment by thesamim** [comment]
That is an unfortunate side effect of the way the Tasks plugin and the TickTickSync plugin clash on click event handling. 

I am working with the Tasks plugin folks to understand how to get around that. Failing which I will figure out a way in TickTickSync to handle that situation.
