### ISSUE TITLE
Feature request - Have a different note for each task

### ISSUE THREAD

**Issue by Lorite** [thesamim/TickTickSync#136]
I think it would be really convenient to have each task in a separate .md file. It would make it easier to refer to the task from other notes and also have longer descriptions and refer to other notes from the task.

To keep compatibility with the Tasks plugin, it would need the task to be part of the note. The tags would be easily added both to the note and to the Obsidian Task. The tick tick description could also be added. It could end up looking like this:

```markdown, Buy eggs.md

# Task

- [ ] Buy eggs ➕ 2024-05-27 📅 2024-05-29

# Description

- Buy the eggs at [[my favourite shop]].
- Bring the eggs for [[my friend]]'s crazy party.

# Other notes

- I don't want this in Ticktick's description.

```

Thank you in advance and let me know if you need any help :)

**Comment by thesamim** [comment]
Interesting suggestion. 

For clarification: you do want the Description in # Description? As opposed to Task Items?

One issue to be handled: there are folks out there with thousands of tasks. I doubt they will want a note for each task. Which means that it would have to be a setting option. And further should include something like "Tasks marked with #onepager" are one Task per page, all others are treated as they are now. Or, alternatively, make it an either or setting....

Thanks for the offer of help. How are you with Typescript and the Obsidian Plugin architecture?

**Comment by Lorite** [comment]
Thanks for the quick reply @thesamim 

I think that the description in Tasks in Obsidian acts as a title and there is no real description. That's why I suggested a separate section. Maybe there is a better way. What do you think?

The idea about making a specific tag for the TickTick tasks that should be a one pager note is a great idea!! It could be configurable to a custom tag. Then, people who want all their tasks to be a one pager note could use "#ticktick".

I have limited knowledge of typescript or obsidian plugins but I'll be happy to try. I usually code in C++ for robotics 😊

**Comment by thesamim** [comment]
> I think that the description in Tasks in Obsidian acts as a title and there is no real description. That's why I suggested a separate section. Maybe there is a better way. What do you think?

So there's actually three attributes that come into play: task.title, task.description, task.items. 

This is a task with a title, no items, no description
![image](https://github.com/thesamim/TickTickSync/assets/5315625/859509f6-e76a-4d3a-918a-355b856a8020)

This is a task with a tile and a description
![image](https://github.com/thesamim/TickTickSync/assets/5315625/8730f4c1-72e1-4059-a34d-6ab546df10eb)

This a task with a title and items
![image](https://github.com/thesamim/TickTickSync/assets/5315625/cfc29c70-54b6-46bc-82b4-f22f5d89487d)

task.description and task.items are mutually exclusive.
task.description can be markdown notes....

I guess it would make sense to have anything in either the task.description or the task.items (whichever one is present) in the 
`# Description` section

**Comment by thesamim** [comment]
Tracking with #168
