### ISSUE TITLE
Can´t login

### ISSUE THREAD

**Issue by ezesolares** [thesamim/TickTickSync#138]
I can´t login to tick tick, its my first time trying it

i just go to setting and try to login.
I get a popup saying

Login Failed. "operation":"Login"
"statusCode":500
"errorMessage":
"errorid":"lajnnvnt@tw9"
"errorCode":"Incorrect_password_too_many_
times"
"errorMessage":"Incorrect_password_too_m
any_times" "data":null}}

and it was the first time i tried the password, then tick tick blocked my account so i had to reset the password

in console i get

Starting Checkpoint date:  Mon Dec 31 2012 19:00:00 GMT-0500 (Peru Standard Time) Checkpoint 1356998400000
plugin:tickticksync:12251
Signed in Response: null
plugin:tickticksync:12283
Starting Checkpoint date: Mon Dec 31 2012 19:00:00 GMT-0500 (Peru Standard Time) Checkpoint 1356998400000
 plugin:tickticksync:12251
Signed in Response: null
plugin:tickticksync:12283

and i dont see in network any rest api request which is weird.

Thanks in advance

**Comment by thesamim** [comment]
@ezesolares : Pardon the delayed response.

Please look in your data.json file (`<your vault root>\.obsidian\plugins\tickticksync\data.json`)

Do you have an entry in `"token"`? (yes or no, please don't copy here.)
What do you see in:
```
"version"
"checkPoint"
```

**Comment by ezesolares** [comment]
First of all, thanks for your work and you have nothing to say sorry.. this is something you give back without asking anything.

I havent tried it again since i posted but now, after seeing your replay i tested it again and it worked.
not sure why, maybe it was because it was a new ticktick account and maybe they have delay between a new account and letting you use the api, not sure.

the data you asked (this was before i tried again)
token was empty
checkPoint was 0
and version was  "1.0.31"

so im not sure what happened but its working now

**Comment by ronilaukkarinen** [comment]
Same happening... it says user and password don't match but they do.
