### ISSUE TITLE
Writing to Incorrect File

### ISSUE THREAD

**Issue by chrisfurlong-aiwyn** [thesamim/TickTickSync#139]
**Describe the bug**
At one point in time, creating a task in Ticktick would write the task to the correct MD file in Obsidian. However, whenever I create a task now, it writes it to an arbitrary daily note and appends it to the bottom-most task.

I removed the file it was selecting, and it simply went to another. I did it again, and it picked a new file from a new directory. The MD file it should be writing to exists, and I've switched the "task directory" for TickTickSync, and created a new file, but to no avail. It's just not respected. 

**To Reproduce**
I have sync enabled across multiple devices but I disabled it and I could still reproduce it. It still seems odd since it's effectively a hard coded file and it shouldn't be allowed to write a new task to a file that wasn't specified (obviously updates may be needed, but imo I don't see a need to insert) 

**Expected behavior**
It should write the task to the same work.md file. 

**Set up questions:
- Is this your first time using TickTickSync? No
- Is your Vault shared across devices?
  - If it is: What Vault synchronization method are you using (eg: Obsidan Sync, Syncthing...)? 

Yes, Obsidian sync 

- Do you have a Default Folder Location?

Yes

- Do you have a Default project?

Yes

- Do you have "Full Vault Sync" enabled?

No but I did at one point 

- Do you have "Debug Mode" enabled?

No

- Do you have either of the "Limit Synchronization" settings set?

No

**Desktop (please complete the following information):**

Chrome / Windows 

**Smartphone (please complete the following information):**

Android 

**Additional context**

**Comment by thesamim** [comment]
@chrisfurlong-aiwyn : 
Is this affecting Inbox tasks, or tasks in a particular list/folder?
For the file that the tasks end up in: did you set that file up a default project for that file?

From your data.json (`<your vault root>\.obsidian\plugins\tickticksync\data.json`), please let me know what entries you have for:
```
defaultProjectName
TickTickTasksFilePath
inboxName
inboxID (just let me know if you have one, don't paste here.)
SyncProject
SyncTag
fileMetadata (note: that's all the file names that TickTickSync knows about. 
         If there's anything sensitive about the naming of those files, please redact. 
        And if you can let me know if you see the file that the tasks are ending up in, 
        and if has a defaultProjectId associated that would be helpful (and the defaultProjectId 
        will match up with one of your project names that would be useful information as well.))
```

**Comment by chrisfurlong-aiwyn** [comment]
Sorry, I missed this - I actually reinstalled the plugin and everything started working again. 

It was going into random files though that were not mentioned anywhere in settings.

**Comment by thesamim** [comment]
thanks for the update. It's still a concern though. If it happens again, please let me know what's in the fileMetaData entry.
