### ISSUE TITLE
Handling Slashes in Tags

### ISSUE THREAD

**Issue by chrisfurlong-aiwyn** [thesamim/TickTickSync#140]
**Describe the bug**

I'm not sure whether to call this a bug, or if it's intended functionality and I'm requesting a feature. When a tag in Obsidian is something like engineering/architecture it is translated directly as such into TickTick. Unfortunately, TickTick doesn't support a "/" character in a tag. 

**To Reproduce**
Create a task in obsidian with a "/" contained in an associated tag

**Expected behavior**
I think the ideal behavior would be to translate it into the TickTick Parent Tag structure, where "engineering" would be the parent tag and "architecture" would be the child tag.

**Comment by thesamim** [comment]
Will consider. 

There are some interesting problems with how TickTick handles the parentage, and it only allows one level of parentage. Obsidian allows unlimited depth.

**Comment by chrisfurlong-aiwyn** [comment]
That's frustrating. If it helps, for my use case, one level would be more than enough. Perhaps the first part <FIRST>/<SECOND>/<THIRD> could be the parent, and if there's a SECOND and THIRD you could replace slashes with hyphens? The problem now is it just translates the slashes as is and it leads to issues. Even a generic hyphen replacement would be appreciated with no parent support

*Chris Furlong*
Chief Technology Officer
***@***.***
www.aiwyn.ai ( http://www.aiwyn.ai )

Sent via Superhuman ( ***@***.*** )

**Comment by thesamim** [comment]
Noted. Will see what I can do....

**Comment by thesamim** [comment]
@chrisfurlong-aiwyn : long story short: it ain't that simple. For right now, replacing all slashes with hyphens on the way up, replacing all hyphens with slashes on the way back.

I'll dig a bit further to see if there's a more rational way to deal with parentage....

**Comment by thesamim** [comment]
slashes in tags are now handled. Right now, the slashes are converted to '-' on the way to Ticktick. And converted to slash on the way back to Obsidian.

When I take care of https://github.com/thesamim/TickTickSync/issues/178, I will work on getting proper parentage for tags. Keeping in mind that TickTick only handles two levels of tag parentage.

**Comment by thesamim** [comment]
see #178
