### ISSUE TITLE
Login Failed Error

### ISSUE THREAD

**Issue by smashasmash** [thesamim/TickTickSync#143]
**Describe the bug**
After entering my user and password in the options I am getting this error (see image attached). My password is correct.

**To Reproduce**
1. Go to 'Settings'
2. Fill out 'User name field' and 'Password'
3. Press 'Login'

**Expected behavior**
I expect to receive some kind of a success message.

**Screenshots**
<img width="310" alt="image" src="https://github.com/thesamim/TickTickSync/assets/11407078/dd445a7e-cac7-46ea-ac7f-515e136c9ff8">

**Set up questions:
- Is this your first time using TickTickSycn? - Yes
- Is your Vault shared across devices? - Yes
  - If it is: What Vault synchronization method are you using (eg: Obsidan Sync, Syncthing...)? iCloud
- Do you have a Default Folder Location? - Don't know what this is
- Do you have a Default project? - Don't know what this is
- Do you have "Full Vault Sync" enabled? - Yes
- Do you have "Debug Mode" enabled? - Yes
- Do you have either of the "Limit Synchronization" settings set? - No

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - MacOS 14.5 (23F79)
 - Browser [e.g. chrome, safari]  - using installed app
 - Version [e.g. 22] - Version 1.6.5 (Installer 1.5.3)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ms3056** [comment]
Your error is different than mine, and your error is very specific - are you sure you are using the right username and password?

**Comment by smashasmash** [comment]
Yes I am, I checked several times :/

**Comment by ms3056** [comment]
OK - I only ask because I am getting this error - nothing about password. 

![image](https://github.com/thesamim/TickTickSync/assets/23712700/143829b9-a984-4eaa-904c-2bec90dcf7e0)

**Comment by ms3056** [comment]
If you have successfully logged in previously, but the plugin suddenly broke, check out my thread here: https://github.com/thesamim/TickTickSync/issues/142#issuecomment-2201691974

If you have a backup of your plugin directory when it did work just copy the working data.json file into your current TickTick Sync plugin directory and it should work fine. I would disable the plugin, copy the file over, then enable it.

**Comment by thesamim** [comment]
@smashasmash : If you are still encountering the problem, go to TickTick and force a password reset and tell me what happens.

**Comment by smashasmash** [comment]
@ms3056 I am very new to Obsidian and do not know where to find the TickTick Sync plugin directory. I have never been able to login successfully. In fact now when I am trying to login, I am getting the same message as you did. 

<img width="319" alt="image" src="https://github.com/thesamim/TickTickSync/assets/11407078/d9baf409-e324-4c4c-be49-0926f49cf9a5">

@thesamim I actually had to reset my password a bunch of times, because I initially signed up through Google's OAuth and didn't even have a password to give this plugin. It's still not working.

**Comment by thesamim** [comment]
@smashasmash : stand by: there appear to be several issues at play here. 

Working on it.

**Comment by smashasmash** [comment]
@thesamim copy that, thank you!

**Comment by thesamim** [comment]
@smashasmash : I've taken care of the 503 error being returned. Not sure if this is going to fix your login issue. But could you please try again 1.0.32?

**Comment by smashasmash** [comment]
@thesamim it works! You are amazing 😃

**Comment by thesamim** [comment]
Thanks @smashasmash @jbarr!
