### ISSUE TITLE
issue with Hiding Comments When DataView is Activated

### ISSUE THREAD

**Issue by Morganwan90** [thesamim/TickTickSync#146]
I've encountered an issue where certain comments are not being hidden when the DataView is activated. Specifically, comments formatted as %%[ticktick_id:: xxxx]%% are being recognized as `dataview inline-field` and remain visible.

strangely, I can normally hide it in both the source view and the preview view, but in the live preview, this format is not hidden.
![image](https://github.com/thesamim/TickTickSync/assets/61633409/63b4b730-af60-4449-92cf-193da0c4eb50)

**Comment by thesamim** [comment]
@Morganwan90 : Could you please share the dataview code block that you're seeing the issue with?

From the inspection you shared (thanks!), it looks like I'm going to have to craft some CSS to only hide TickTickSync comments... Or figure out whey dataview is seeing the ID as inline-field.

I'm *assuming* that you don't want ALL inline fields hidden, just the TickTick ID?

**Comment by Morganwan90** [comment]
## Method to Reproduce This Issue:
### Input Test Document
Enter the following text in the document:
```
- [ ] test1 %%testcomment%%
- [ ] test2 %%[testcomment2:: 11]%%
```
### Problem Encountered
#### When the Dataview Plugin is Disabled
![image](https://github.com/thesamim/TickTickSync/assets/61633409/3e0b1576-fdcd-485f-b90e-01e2c6fd9868)
#### After Enabling the Dataview Plugin
![image](https://github.com/thesamim/TickTickSync/assets/61633409/8bc0df1c-8eb1-4ee1-b325-ec0401ab6262)


I have conducted some tests. When the matching format is [A:: B], it will recognize A and B as the key and value of the dataview inline-field, regardless of whether %%%% has been added.

Then, yes, I only want to hide the ticktick comments. Although I use this feature less frequently now, to avoid potential issues, it is more in line with my requirements to only hide ticktick comments.

**Comment by thesamim** [comment]
@Morganwan90 : could you please try the following: 

```
.dataview.inline-field-key[data-dv-key="ticktick_id"],
.dataview.inline-field-key[data-dv-key="ticktick_id"] + span {
  display: none;
} 
```

**Comment by Morganwan90** [comment]
> @Morganwan90 : could you please try the following:
> 
> ```
> .dataview.inline-field-key[data-dv-key="ticktick_id"],
> .dataview.inline-field-key[data-dv-key="ticktick_id"] + span {
>   display: none;
> } 
> ```

It works!
There are some differences from my original code display. Your code shows this when hovering:
![image](https://github.com/thesamim/TickTickSync/assets/61633409/5b9c4354-484e-4b4f-814e-f8a53b13ad10)

It only shows ticktick when clicked in between the `%%`.
![image](https://github.com/thesamim/TickTickSync/assets/61633409/03273ce0-5a4c-4ff8-b809-6d7527fed5f2)


For me, it already solves my problem very well, thank you!

**Comment by thesamim** [comment]
Glad that helped. Could you please try adding the following:
```
.cm-line span.cm-comment {
    display: none;
}

.cm-line.cm-active span.cm-comment,
.cm-line:hover span.cm-comment {
    display: inline-block;
}
```

**Comment by Morganwan90** [comment]
> Glad that helped. Could you please try adding the following:
> 
> ```
> .cm-line span.cm-comment {
>     display: none;
> }
> 
> .cm-line.cm-active span.cm-comment,
> .cm-line:hover span.cm-comment {
>     display: inline-block;
> }
> ```

The code seems not to hide `[[ticktick_id:: XXX]]`; it still appears as `.dataview.inline-field`.
I combined the previous code with your code to become:
```
.cm-line span.cm-comment,
.dataview.inline-field-key[data-dv-key="ticktick_id"],
.dataview.inline-field-key[data-dv-key="ticktick_id"] + span {
  display: none;
}

.cm-line.cm-active span.cm-comment,
.cm-line.cm-active .dataview.inline-field-key[data-dv-key="ticktick_id"],
.cm-line.cm-active .dataview.inline-field-key[data-dv-key="ticktick_id"] + span,
.cm-line:hover span.cm-comment,
.cm-line:hover .dataview.inline-field-key[data-dv-key="ticktick_id"],
.cm-line:hover .dataview.inline-field-key[data-dv-key="ticktick_id"] + span {
  display: inline-block;
}
```
And it works perfectly! Although it doesn't look particularly neat, it effectively hides all `%%[[ticktick_id::xxx]]` and fully displays them when the active line and hover conditions are met!
