### ISSUE TITLE
Inbox not being created or synched from TickTick to Obsidian

### ISSUE THREAD

**Issue by ms3056** [thesamim/TickTickSync#151]
If I leave this empty, I saw Work and Personal folders come over into the folder TickTick - the files were created, and the tasks were in them. 

I ONLY want Inbox to come over. When I have the settings like this no Inbox file is created. I created a Inbox file manually, restarted Obsidian, and nothing happens. 

This could be my lack of understanding or operator error - sorry if it is!

![image](https://github.com/thesamim/TickTickSync/assets/23712700/b926ef3d-a040-44f0-89d3-32ceee1e67f0)

**Comment by thesamim** [comment]
@ms3056 : With your current settings, you should have a folder /TickTick and you should have a file Inbox.md in that folder. So:
`/TickTick/Inbox.md`

The settings will only sync the Inbox project (called a list in TickTick.)

If this is not happening please check:

1. Do you have the file in the folder?
2. Is the capitalization the same? (ie: Inbox.md, NOT inbox.md)
3. Is the file writable?

If you answered yes to all of those, please turn on "Debug Mode" in settings and send me the console log.

**Comment by ms3056** [comment]
Thanks for the reply. I creeated a file in TickTick called Inbox.md. It is writable. Note - I have a folder at my root level called Inbox - but there are no other files or folders named Inbox in my vault. 

TickTick scheduled synchronization task started at 7/14/2024, 1:40:05 PM
plugin:tickticksync:22881 We have:  162  tasks on https://api.ticktick.com/api/v2
plugin:tickticksync:22884 openTasks 3 closedTasks 159
plugin:tickticksync:22889 There are:  273  tasks in Cache.
plugin:tickticksync:22972 No synchronization changes.
plugin:tickticksync:21908 Duplicate check Skipping  Journal/Daily/2024/2024-12  because it's a folder.
plugin:tickticksync:23594 Journal/Daily/2024/2024-05/2024-05-30.md
3plugin:tickticksync:20562 #### get all tags ticktick
plugin:tickticksync:20562 #### get all tags obs
3plugin:tickticksync:20562 #### get all tags ticktick
plugin:tickticksync:20562 #### get all tags atag
plugin:tickticksync:20562 #### get all tags ticktick
plugin:tickticksync:20562 #### get all tags atag
plugin:tickticksync:20562 #### get all tags atag
6plugin:tickticksync:20562 #### get all tags ticktick
plugin:tickticksync:20562 #### get all tags atag
plugin:tickticksync:20562 #### get all tags ticktick
plugin:tickticksync:20562 #### get all tags anothertag
3plugin:tickticksync:20562 #### get all tags ticktick
plugin:tickticksync:20635 The timestamps are different, but not calculatable..
plugin:tickticksync:22424 Due date modified for task 663b23bc0356c56bb072237d
plugin:tickticksync:22425 new:  2024-05-07T15:00:00.000+0000 old:  
plugin:tickticksync:22538 Task Changed:  663b23bc0356c56bb072237d 
 Task 663b23bc0356c56bb072237d is updated.
Due date was changed.
78plugin:tickticksync:20562 #### get all tags ticktick
plugin:tickticksync:20562 #### get all tags work
38plugin:tickticksync:20562 #### get all tags ticktick
plugin:tickticksync:20562 #### get all tags atag
3plugin:tickticksync:20562 #### get all tags ticktick
plugin:tickticksync:23594 Journal/Daily/2024/2024-07/2024-07-03.md
3plugin:tickticksync:20562 #### get all tags ticktick
plugin:tickticksync:23594 Journal/Notes/2024-Jul/20240701085705.md
plugin:tickticksync:20562 #### get all tags atag
plugin:tickticksync:20562 #### get all tags ticktick
plugin:tickticksync:23594 Journal/Notes/2024-Jul/20240705073651.md
plugin:tickticksync:20562 #### get all tags atag
plugin:tickticksync:20562 #### get all tags ticktick
plugin:tickticksync:23626 TickTick scheduled synchronization task completed at 7/14/2024, 1:40:09 PM


![image](https://github.com/user-attachments/assets/0b61fbf5-f82a-4b3a-a1b1-b55d358f93d0)

**Comment by ms3056** [comment]
I think I see - I wanted the TickTick main folder Inbox to the sync folder but it is looking for a list. I think I understand now. 

![image](https://github.com/user-attachments/assets/5cc9f514-8af7-489d-bfa5-7cd7cc6cde08)

**Comment by thesamim** [comment]
Actually, it should be picking up Tasks from the Inbox list as well.

Please try this:

1. Add a task to Inbox.md, give it a `#ticktick` tag.
2. Add a task to Inbox in Ticktick.
3. Synchronize

Tell me what happens.

**Comment by thesamim** [comment]
@ms3056 : 
Is this still an issue?
