### ISSUE TITLE
Installed plugin, logged in, not able to sync tasks

### ISSUE THREAD

**Issue by paulsybrandy** [thesamim/TickTickSync#155]
Okay, I am most likely missing something so small but as I am human this does happen from time to time. I installed and enabled the plugin; I logged in with username and password in the settings but cannot seem to be able to pull I my ticktick tasks into obsidian. I tried using dataview as well as the tasks plugin but to no avail. Please help.

**Comment by thesamim** [comment]
> [...] cannot seem to be able to pull I my ticktick tasks into obsidian. 

You've probably done nothing wrong. TickTick periodically acts stupid and we have to work on what it's current issue is.

What platform are you on and what version of the plugin are you using?

To find out what's going on, please: 

1. turn on "Debug Mode" in settings.
2. access the debug console (Ctrl-Shift I on Windows, similar keystrokes in Mac. More complex on mobile.)
3. login
4. send me what you see in the console.

Also, don't be surprised if it suddenly just starts working. :)

**Comment by thesamim** [comment]
@paulsybrandy 
Please update to the latest release. Let me know if you're still having issues. If you are: Please open a new ticket.
