### ISSUE TITLE
Enhancement Request: Option to sync TickTick Notes

### ISSUE THREAD

**Issue by ms3056** [thesamim/TickTickSync#156]
I see the api supports the sync of TickTick notes. It would be an interesting use case to capture notes in TickTick and have them sync over to notes in Obsidian. 

I would use this as a "quick entry" method on mobile - I would make a note in TickTick on iOS, then when I go to my PC I would see the note appear in my TickTick directory as an .md file. 

I think this could be a bit of a game changer, honestly.

**Comment by thesamim** [comment]
@ms3056 : that's a feature that's been requested before. 

The challenge: how do the notes look like in Obisidian? I'm open to suggestions.

**Comment by Dennyyusuf** [comment]
Second to this feature, this will be a game changer.

My current workflow is to input any task related to the project and edit it later in Obsidian. If we can add more context to the task description in TickTick and sync it with Obsidian, that would be great.

We spend most of our time on mobile while on the go, so having bidirectional sync would be very convenient."

**Comment by ms3056** [comment]
> @ms3056 : that's a feature that's been requested before. 
> 
> 
> 
> The challenge: how do the notes look like in Obisidian? I'm open to suggestions. 
> 
> 

One idea - keep it simple. Settings would be a folder in your vault, each note in TickTick would be a note in Obsidian. 

If no-directional is not possible, for me, one way TickTick to Obsidian would be a game changer. TickTick is quick to load and jotting down something there and having it show up in Obsidian for processing later would potentially eliminate my need for Obsidian Sync honestly. I'd probably keep it to support the devs but for me my potable devices are capture only - processing the info is all done in Obsidian on my laptop.

**Comment by Dennyyusuf** [comment]
> > @ms3056 : that's a feature that's been requested before.
> > The challenge: how do the notes look like in Obisidian? I'm open to suggestions.
> 
> One idea - keep it simple. Settings would be a folder in your vault, each note in TickTick would be a note in Obsidian.
> 
> If bi-directional is not possible, for me, one way TickTick to Obsidian would be a game changer. TickTick is quick to load and jotting down something there and having it show up in Obsidian for processing later would potentially eliminate my need for Obsidian Sync honestly. I'd probably keep it to support the devs but for me my potable devices are capture only - processing the info is all done in Obsidian on my laptop.

Agree, can't wait if it s doable and possible in the near future..

**Comment by thesamim** [comment]
@ms3056 , @Dennyyusuf , @jgindin , @quanru : 

I like the idea of a separate folder by note. It would certainly make bi-directional sync cleaner. If we all agree this is a viable solution, I will start on it ASAP.

Unrelated, but it doesn't hurt to ask:
Any of y'all have any experience removing malware from hosted web sites? And keeping the malware out? If you do, I would appreciate any assistance as I'm over my head trying to clean up some personal web sites.

Thanks in advance.

**Comment by Dennyyusuf** [comment]
> @ms3056 , @Dennyyusuf , @jgindin , @quanru :
> 
> I like the idea of a separate folder by note. It would certainly make bi-directional sync cleaner. If we all agree this is a viable solution, I will start on it ASAP.
> 
> Unrelated, but it doesn't hurt to ask: Any of y'all have any experience removing malware from hosted web sites? And keeping the malware out? If you do, I would appreciate any assistance as I'm over my head trying to clean up some personal web sites.
> 
> Thanks in advance.

Yes Sir,

Your contributions to the TickTick and Obsidian communities have been tremendously valuable.

**Comment by ms3056** [comment]
> @ms3056 , @Dennyyusuf , @jgindin , @quanru :
> 
> I like the idea of a separate folder by note. It would certainly make bi-directional sync cleaner. If we all agree this is a viable solution, I will start on it ASAP.
> 
> Unrelated, but it doesn't hurt to ask: Any of y'all have any experience removing malware from hosted web sites? And keeping the malware out? If you do, I would appreciate any assistance as I'm over my head trying to clean up some personal web sites.
> 
> Thanks in advance.

Hmmm - I would say "TickTick notes are a separate Obsidian note, in a single folder you setup in settings". Like:

TickTick Notes (folder)
- TickTick Note 1.md
- TickTick Note 2.md
-

**Comment by thesamim** [comment]
Tracking with #168
