### ISSUE TITLE
Unable to Login to New Account

### ISSUE THREAD

**Issue by Adanufgail** [thesamim/TickTickSync#157]
**Describe the bug**
Receiving a 500 error "incorrect_password_too_many_times" on the first attempt to log in with a brand new account.

**To Reproduce**
1. Install Plugin
2. Enable Plugin
3. Enter Username/Password
4. Click "Login"

**Expected behavior**
Log in

**Screenshots**

![2024-08-23 13_55_31](https://github.com/user-attachments/assets/110d02d1-e5e1-4e79-8975-7629c922e989)

**Set up questions:
- Is this your first time using TickTickSycn? Yes
- Is your Vault shared across devices? Yes, Obsidian Sync
  - If it is: What Vault synchronization method are you using (eg: Obsidan Sync, Syncthing...)? 
- Do you have a Default Folder Location? Vault Root
- Do you have a Default project? No
- Do you have "Full Vault Sync" enabled? No
- Do you have "Debug Mode" enabled? Yes
- Do you have either of the "Limit Synchronization" settings set? No

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Obsidian Desktop
 - Version: v1.6.7

**Additional context**
I've tried the following:

1. Restart Obsidian
2. Remove the plugin, restart Obsidian, add the plugin, restart Obsidian
3. Change my password to not have any special characters other than hypens and underscores.

I was able to log into TickTick in an incognito window with the Username/Password I put into the plugin.

From the Debug Log:

plugin:tickticksync:12251 Starting Checkpoint date:  Mon Dec 31 2012 17:00:00 GMT-0700 (Mountain Standard Time) Checkpoint 1356998400000
plugin:tickticksync:12283 Signed in Response:  null

**Comment by thesamim** [comment]
In the data.json file in your plugin folder (let me know if you need help finding it), there's a checkpoint entry. The checkpoint entry will be 1356998400000 . Try changing that to 1662839705 and let me know what happens.

**Comment by Adanufgail** [comment]
Tested again and now its working after recent updates

**Comment by thesamim** [comment]
@Adanufgail : Thanks for the update.
