### ISSUE TITLE
Date not working in Obsidian

### ISSUE THREAD

**Issue by kmaustral** [thesamim/TickTickSync#16]
Icon for date schedule is placed incorrectly. 

`#ticktick 🗓️ 2023-12-23  %%[ticktick_id:: 658780b534d3c52c8d949e38]%%`

This does not appear in a Tasks query. The date needs to be at the end of the task, like this:

`#ticktick  %%[ticktick_id:: 658780b534d3c52c8d949e38]%% 🗓️ 2023-12-23`

None of my tasks have a time, so it would be good to allow for an all-day task.

**Comment by thesamim** [comment]
Noted. Will investigate.

**Comment by tccc90** [comment]
I used this along with Obsidian task plugin with recurring task. 
- The recurrence pattern "🔁 every day when done " should be put before due date expression "📅 2024-10-01" else task plugin wont generate new task when a existing task get completed.
- tickticksync always overwrite the due date to schedule date symbol to due date symbol. Not an issue for me, just to point out my experience.
- tickticksync plugin interpreted the recurrence pattern as text. i wish that could be added in the future.

thank you so much for developing this plugin.

**Comment by thesamim** [comment]
@tccc90 : On the horizon: https://github.com/thesamim/TickTickSync/issues/97
