### ISSUE TITLE
Login error 429 status code

### ISSUE THREAD

**Issue by badralbanna** [thesamim/TickTickSync#160]
**Describe the bug**
Yesterday, I was prompted to log back in to my tick tick account, but when I did I received an error with the message

{"operation": "Login", 
"statusCode": 429,
"errorMessage": ""} 

I assumed waiting a day would help, but I am still receiving the same message. I tried changing my password to TickTick but it did not affect the problem. 

**Set up questions:
- Is this your first time using TickTickSync? No. It has been working properly for about a week. 
- Is your Vault shared across devices? Yes, on another desktop. 
  - If it is: What Vault synchronization method are you using (eg: Obsidan Sync, Syncthing...)? git
- Do you have a Default Folder Location? Yes. 
- Do you have a Default project? Yes.
- Do you have "Full Vault Sync" enabled? Yes.
- Do you have "Debug Mode" enabled? ~~I tried this, but I didn't see any additional messages in the console for this error.~~ 
- Do you have either of the "Limit Synchronization" settings set? I did, but those settings are no longer visible.  

**Desktop (please complete the following information):**
- OS: macOS 14.3 
- Obsidian Version: 1.6.7
- Plugin version: 1.0.32

**Comment by badralbanna** [comment]
OK, I am seeing something in the console: 

<img width="736" alt="Screenshot 2024-09-17 at 10 04 35 AM" src="https://github.com/user-attachments/assets/09be3be3-03d9-4b47-bca5-331477c96622">

**Comment by netdevdan** [comment]
Same issue here and with the above steps.

**Comment by legleux** [comment]
I'm hitting this also.

Is this what is causing the notification "Please login from settings?" I can't tell where that's coming from.

**Comment by netdevdan** [comment]
> I'm hitting this also.
> 
> Is this what is causing the notification "Please login from settings?" I can't tell where that's coming from.

Yes

**Comment by IMXeno123** [comment]
@legleux @netdevdan @badralbanna [try this](https://github.com/thesamim/TickTickSync/issues/159#issuecomment-2356984233) :)

**Comment by techyogi** [comment]
Same issue.
