### ISSUE TITLE
Reopen issue 159

### ISSUE THREAD

**Issue by NighteyesWolf** [thesamim/TickTickSync#165]
https://github.com/thesamim/TickTickSync/issues/159

I'm so sorry, I'm not sure how to request an existing issue is reopened - people have added comments on the issue (linked above) but I'm not sure they'll be getting through to you in the normal ways because the issue is marked as "closed".

Thank you so much for all your support.

**Comment by thesamim** [comment]
@ms3056, @IMXeno123 , @Dennyyusuf , @jee-ee , @NighteyesWolf , @jgindin :
Took a gamble that my testing is complete and release 1.0.34 before giving to y'all for testing to save a test. 

Please open a new ticket if anything goes wrong.
