### ISSUE TITLE
Usage Question - Obsidian > TickTick and back

### ISSUE THREAD

**Issue by ms3056** [thesamim/TickTickSync#167]
Hi - I have a usage question. 

Setup: I have a specific Project in the settings to sync from TickTick > Obsidian, called Sync. I have a tag setup for syncing tasks called ticktick (like #ticktick) 

1. I create a task in Obsidian, with #ticktick and the plugin puts it into my Inbox (note this is not the Sync project)
2. This task appears in TickTick - awesome
3. If I check the task in Obsidian it checks in TickTick - awesome 
4. If I check the task in TickTick it does NOT check the task in Obsidian

Is this by design, because I have setup the project Sync as the project to sync? I don't want ALL my TickTick tasks coming over, but, it would be nice if the tasks originating in Obsidian, with, in my case, the #ticktick in the task, to be bi-directional. 

So - is something broken or is this working as intended?

**Comment by thesamim** [comment]
> So - is something broken or is this working as intended?

This is broken. It should be completely bi-directional.

From you data.json under the plugin directory please let me know the contents of:
```
"defaultProjectId": 
"defaultProjectName": 
"SyncProject"
"SyncTag" 
```

**Comment by ms3056** [comment]
```json
"defaultProjectId": "6693804feb76f60000000177"
"defaultProjectName": "Inbox"
"SyncProject": "6693804feb76f60000000177"
"SyncTag": "ticktick"
```

**Comment by thesamim** [comment]
@ms3056 
Question: The tasks that are not getting completed from TickTick, are they in a file that is associated with  a project other than the project you are limiting the syncing to? (Note: The Project/List to File association happens at the file level, not the directory level.)

**Comment by ms3056** [comment]
> @ms3056 Question: The tasks that are not getting completed from TickTick, are they in a file that is associated with a project other than the project you are limiting the syncing to? (Note: The Project/List to File association happens at the file level, not the directory level.)

No - the tasks are in a different file structure. The use case I am trying for:

1. Tasks from Obsidian tagged with #ticktick from any page any "project" are synced to TickTick and bi-directionally sync'd 
2. Task from TickTick in the Sync project are sync'd over to Obsidian

2 is working fine. 
1. is not - I suspect - because the tasks from Obsidian are not in Sync and are in my daily note. They make it to TickTick but clicking them off in TickTick doesn't check them off in Obsidian - probably by design - that's what I am trying to figure out. 

My Sync project is in the folder TickTick/Sync.md. My tasks I create in Obsidian are usually in my Daily Note or meeting notes which are in the structure Journal/Daily/YYYY/YYYY-MM/2024-10-04.md or Journal/Notes/YYYY-MMM. 

I hope that makes sense. Again - if the reason for the lack of bi-directional sync is because of the project being set to Sync and my tasks in the  Journal folders let me know.

**Comment by thesamim** [comment]
> I hope that makes sense. Again - if the reason for the lack of bi-directional sync is because of the project being set to Sync and my tasks in the Journal folders let me know.

Yes it is.

**Comment by ms3056** [comment]
> Yes it is. 

Thanks - so if I tag the task with #sync and #ticktick then it should be bi-directional even if the tasks resides in my Journal folder?

**Comment by thesamim** [comment]
> > Yes it is.
> 
> Thanks - so if I tag the task with #sync and #ticktick then it should be bi-directional even if the tasks resides in my Journal folder?

Not yet. The original intent was for the tag to be a second limit on the project. But it actually makes sense for it to work the way you just described. I will test some more and include in the next release.
