### ISSUE TITLE
Most completed tasks (but also some undue) were trashed 

### ISSUE THREAD

**Issue by machado-t** [thesamim/TickTickSync#17]
First of all, thank you for working on this plugin!
Unfortunately, in my case, it didn't worked out perfectly.
It seems that all previously completed tasks were trashed, as well as some due tasks as well. 
I have no idea why this happened. I have not deleted or edited any of the files created by the plugin.
I have since tried to restore the automatic backup but all the trashed tasks continue deleted. For me this is not a huge inconvenience. I don't care that completed tasks are now deleted, and any deleted task that is not completed I have since manually restored.
Also, a lot of tasks that were completed a long time ago now appear as completed on the day I installed the plugin.
I have now uninstalled the plugin, but will love to give it another try in the future. I cannot send you my files due to confidentiality issues, but let me know if I can help you figure this out in any way. I was using version 1.0.6

**Comment by thesamim** [comment]
Completed tasks should not be trashed.  If you are able to recall how you get to that point, that would be helpful.

Meanwhile, if you go to https://ticktick.com/webapp/#q/all/trash, do you see your tasks there?

**Comment by machado-t** [comment]
There's not much to I can say regarding how this happened. I installed the plugin a few days ago, and since only tested it creating a couple of tasks with it. Maybe I should mention that I use OneDrive for syncing between devices, which often results in conflict files, but I didn't even notice any problems with that.

Yes, my tasks are in the trash, and I have restored the few that were not completed. 
Actually, not all completed tasks were trashed, but all completed tasks from certain lists.

**Comment by thesamim** [comment]
> Actually, not all completed tasks were trashed, but all completed tasks from certain lists.

That's a good data point. If there's no confidential information in the list names themselves, could you please give me a list of your lists (a screenshot would do) and let me know which lists you had the problem with?

**Comment by thesamim** [comment]
> Maybe I should mention that I use OneDrive

I haven't actually tested with this. One issue I can see coming up with that: When OneDrive finds conflicts it duplicates the conflicting files with additional information in their names eg: <original file name>-<conflicting machine name>.md If the file happens to contain synced tasks, TickTickSync will attempt to update them. I'm not sure what will happen with that.

**Comment by machado-t** [comment]
> > Maybe I should mention that I use OneDrive
> 
> I haven't actually tested with this. One issue I can see coming up with that: When OneDrive finds conflicts it duplicates the conflicting files with additional information in their names eg: <original file name>-<conflicting machine name>.md If the file happens to contain synced tasks, TickTickSync will attempt to update them. I'm not sure what will happen with that.

Good point, but I didn't find any duplicate files, as usually happens.

**Comment by machado-t** [comment]
> > Actually, not all completed tasks were trashed, but all completed tasks from certain lists.
> 
> That's a good data point. If there's no confidential information in the list names themselves, could you please give me a list of your lists (a screenshot would do) and let me know which lists you had the problem with?

Sent by email. Thanks
