### ISSUE TITLE
Login failure: operation "Get Inbox Properties" reports error 429 "TickTick reporting too many requests"

### ISSUE THREAD

**Issue by bluebirch** [thesamim/TickTickSync#170]
**Describe the bug**

Trying to log in for the first time (haven't been able to make the plugin work). I do get server error 429, "TickTick reporting too many requests".

I have tried waiting 6 hours, but that didn't help.

**To Reproduce**

1. Install and activate plugin.
2. Enter username and password and click login.

**Expected behavior**

The plugin works.

**Screenshots**

![image](https://github.com/user-attachments/assets/ecb2c2d4-985e-479d-a816-3790938487a4)

**Set up questions:
- Is this your first time using TickTickSycn? **Yes.***
- Is your Vault shared across devices? **Yes.**
  - If it is: What Vault synchronization method are you using (eg: Obsidan Sync, Syncthing...)? **Synology Drive**
- Do you have a Default Folder Location?
- Do you have a Default project?
- Do you have "Full Vault Sync" enabled?
- Do you have "Debug Mode" enabled?
- Do you have either of the "Limit Synchronization" settings set?

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Brave
 - Version 

**Additional context**

Tried many of the workarounds in the older issues but none of them worked.

**Comment by thesamim** [comment]
@bluebirch : Is this with the [1.0.34](https://github.com/thesamim/TickTickSync/releases/tag/1.0.34) version?

If not, please try with that version.

If it: Please try uninstalling the plugin and re-installing it and tell me what happens.

**Comment by bluebirch** [comment]
Tried 1.0.34 and latest version from GitHub with BRAT.

After uninstall and re-install, i get error 500 and "username_password_not_match". I fixed that one before with the fix in #159 and some other fix where I changed the "version" numbering, so this is one step backwards.

**Comment by bluebirch** [comment]
I enabled debug, clicked "login"... and it worked. What? I didn't do anything.

**Comment by thesamim** [comment]
> I enabled debug, clicked "login"... and it worked. What? I didn't do anything.

Long story short: TickTick requires unique 'User-Agent' and 'x-device' headers. When the plugin is first installed, it  tries to generate those for you. Given the limitations of randomness in JavaScript, it's entirely possible that the first set it generated was already used elsewhere. (In the not distant future, I will figure out a better way of handling that.) It does have a retry mechanism, but it's not as reliable as I want it to be. Anyway: so in re-installing and enabling debug, you hit the magic number of retries to get you past the uniqueness issue. 

Glad it's working. Hope this helped.

**Comment by bluebirch** [comment]
It's currently syncing hundreds of completed tasks over the last decade or so...

**Comment by thesamim** [comment]
Fixed with https://github.com/thesamim/TickTickSync/pull/173
