### ISSUE TITLE
Reminder time added at end of line breaks obsidian tasks

### ISSUE THREAD

**Issue by blahnika** [thesamim/TickTickSync#177]
**Describe the bug**
When adding a reminder time in TickTick, it then syncs back to Obsidian and adds the HH:mm at the end of the line after the due date. If you are using the tasks plug in, when you do a query on due today, even if the date is today it doesn't show up. Since task doesn't support time, it creates a problem. 

**To Reproduce**
Take a task that has a due date and add a reminder time in Tick Tick 
Sync to obsidian and it adds the HH:mm at the end of that tasks. 
If you're using the tasks plug in, do a filter for something like "due today" and even if that date is today it doesn't sync. 

**Expected behavior**
Since Tasks doesn't support Time, either remove it, or git the ability in options to remove that from syncing, or add it somewhere else in the line so it doesn't break the tasks plugin ability to filter. 

**Screenshots**
N/A

**Set up questions:
- Is this your first time using TickTickSycn? No
- Is your Vault shared across devices? Yes, using remote sync
  - If it is: What Vault synchronization method are you using (eg: Obsidan Sync, Syncthing...)? 
- Do you have a Default Folder Location? Yes
- Do you have a Default project? Yes
- Do you have "Full Vault Sync" enabled? No
- Do you have "Debug Mode" enabled? No
- Do you have either of the "Limit Synchronization" settings set? No

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 15

**Additional context**
Only a problem if you use Tasks and want to do a filter on the due date

**Comment by thesamim** [comment]
Will be addressed with https://github.com/thesamim/TickTickSync/issues/97

**Comment by blahnika** [comment]
Nice, didn't see that one when I am searching, but its the same thing.
