### ISSUE TITLE
Unable to log in (error 429)

### ISSUE THREAD

**Issue by Dennyyusuf** [thesamim/TickTickSync#179]
**Describe the bug**
Unable to log in:
![image](https://github.com/user-attachments/assets/aea07517-2f0c-4be7-b89e-789628a95367)

I was suddenly logged out and keep receiving an error message when trying to log back in.

**Comment by pflajszer** [comment]
same here

**Comment by Maikl3** [comment]
I have the same thing

**Comment by programgames** [comment]
Same today as yesterday

**Comment by thesamim** [comment]
@badralbanna @programgames @pflajszer @Maikl3 @Dennyyusuf :
TickTick wins the game of cat and mouse today. Sorry.

I have pushed version 1.0.36, but that won't fix the problem.

Here's a very dirty work around:

1. Log in to TickTick in a web browser.
2. In the web browser, go to developer mode (F12 for most browsers, Ctrl-I for some browsers.)
3. Go to the "Applications" tab.
4. Go to the Cookies Entry
5. Look for the "t" Cookie. 
6. Copy the content of the cookie

![browserApplicationCookie](https://github.com/user-attachments/assets/d6534679-0e2f-4821-be71-74c127c6c69a)

Now go to `<vault>\.obsidian\plugins\TickTickSync\data.json`

1. Look for `"token":`
2. paste the cookie contents between quotes
3. restart obsidian

It should look like this:
`"token": "154BB8FE914467833[....]"`

Let me know what happens.

**Comment by pflajszer** [comment]
it doesn't work without updating, and it won't let me update:

![image](https://github.com/user-attachments/assets/99cddffe-47a6-4585-afad-0d0730253f92)

**Comment by pflajszer** [comment]
also, it appears that the latest version in github is 1.0.35 when looking under Releases, so perhaps that's where the 404s coming from?

**Comment by thesamim** [comment]
@pflajszer : Missed a file in the last commit. Please try again. 1.0.36 is out there for real now.

**Comment by thesamim** [comment]
That folder is created the first time you install the plugin and enable it. If you are not seeing that folder, something else is going on. 

But, ya, I was not expecting that release to fix the problem. We still need to go through https://github.com/thesamim/TickTickSync/issues/179#issuecomment-2414566587

**Comment by Maikl3** [comment]
> @badralbanna @programgames @pflajszer @Maikl3 @Dennyyusuf : TickTick wins the game of cat and mouse today. Sorry.
> 
> I have pushed version 1.0.36, but that won't fix the problem.
> 
> Here's a very dirty work around:
> 
> 1. Log in to TickTick in a web browser.
> 2. In the web browser, go to developer mode (F12 for most browsers, Ctrl-I for some browsers.)
> 3. Go to the "Applications" tab.
> 4. Go to the Cookies Entry
> 5. Look for the "t" Cookie.
> 6. Copy the content of the cookie
> 
> ![browserApplicationCookie](https://private-user-images.githubusercontent.com/5315625/376715941-d6534679-0e2f-4821-be71-74c127c6c69a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMjA0NzMsIm5iZiI6MTcyOTAyMDE3MywicGF0aCI6Ii81MzE1NjI1LzM3NjcxNTk0MS1kNjUzNDY3OS0wZTJmLTQ4MjEtYmU3MS03NGMxMjdjNmM2OWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTVUMTkyMjUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODNmMzkzMzg2NzkxMzY3NjE1ODVhNjc3YTg5NzM3NDg2MzhiY2NjYzM4ZDgxZGJkMmQwZGQwZjdkY2FjYjk3ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.6rx85JKntdm92rlpEDXp4nFT1SwriHYTmycPg93V6gc)
> 
> Now go to `<vault>\.obsidian\plugins\TickTickSync\data.json`
> 
> 1. Look for `"token":`
> 2. paste the cookie contents between quotes
> 3. restart obsidian
> 
> It should look like this: `"token": "154BB8FE914467833[....]"`
> 
> Let me know what happens.

Yes, it worked! Thanks!

**Comment by badralbanna** [comment]
Also worked here. Thank you!!!

**Comment by Dennyyusuf** [comment]
it works! thanks! 

cheers

**Comment by badralbanna** [comment]
Sadly I'm back to getting 429s after a day. Appreciate all the efforts but Ticktick is not making this easy!

**Comment by thesamim** [comment]
> Sadly I'm back to getting 429s after a day. Appreciate all the efforts but Ticktick is not making this easy!

My current theory is that TickTick is only checking the x-device parameter on Login. Meaning that if you get logged in, and stay logged in, you shouldn't encounter the 429 again.

Are you getting the 429 on login, or are you getting on synchronization?

**Comment by badralbanna** [comment]
Both

**Comment by badralbanna** [comment]
OK weird, I think I must have somehow accidentally obliterated the `token` I added before. Just put it back and things are working. (still get 429s on login though but sync seems to be working)

**Comment by thesamim** [comment]
> OK weird, I think I must have somehow accidentally obliterated the `token` I added before. Just put it back and things are working. (still get 429s on login though but sync seems to be working)

that confirms the theory about x-device and login, thanks. 

Sill working on that black magic....

**Comment by ms3056** [comment]
For me the steps that worked:

1. Close obsidian
2. Open Chrome
3. Clear browser history
4. Log in to TickTick
5. Copy the token value
6. Paste into the `data.json` file
7. Start Obsidian
8. WIN!

**Comment by johnyoonh** [comment]
it would be great if the setting page has a form field to paste token

**Comment by thesamim** [comment]
@ms3056, @badralbanna : Is that still happening today?

I'm still working on figuring out the pattern by the way, haven't abandoned y'all.

**Comment by thesamim** [comment]
> Any update on progress of the fix for this? Seems to be working temporarily. And then not at all again.

Several of my theories have been disproven. So, still working on it and try to find  a more solid fix.

Q: What's your refresh interval set at?

**Comment by turts121** [comment]
> > Any update on progress of the fix for this? Seems to be working temporarily. And then not at all again.
> 
> Several of my theories have been disproven. So, still working on it and try to find a more solid fix.
> 
> Q: What's your refresh interval set at?

Refresh rate is set at default of 300. 
Just cleared browser cookie cache, relogged in on browser (edge), copied token and placed in the ticticksync/data.json file. Didn't work at all this time now. I get an immediate set of three errors as shown below. Re-input login data into the plugin, and get greated with the error 429 again.

![image](https://github.com/user-attachments/assets/9594ecc1-9f4d-4da9-8a74-26846db70fcb)

Appreciate your efforts in this!

**Comment by thesamim** [comment]
Could you please try:

1. Close Obsidian
2. in data.json modify the following settings:
```
  "initialized": true,
  "apiInitialized": true,
```
3. Restart Obsidian.
4. Do NOT login.
5. Try forcing a  Sync.

Let me know what happens.

**Comment by turts121** [comment]
> Could you please try:
> 
> 1. Close Obsidian
> 2. in data.json modify the following settings:
> 
> ```
>   "initialized": true,
>   "apiInitialized": true,
> ```
> 
> 3. Restart Obsidian.
> 4. Do NOT login.
> 5. Try forcing a  Sync.
> 
> Let me know what happens.

Followed - resulted in getting the following.
![image](https://github.com/user-attachments/assets/9d7aefcc-8af8-4b05-872f-ba4f383c5308)
Checked Ticktick on the browser though and there doesn't appear to be any updates.

**Comment by thesamim** [comment]
"Sync Completed" kinda indicates that we've tricked the plugin into thinking it's logged. 

In settings, turn "Debug Mode" on. Take a look at the console on next sync. You should see the number of tasks the plugin sees....

**Comment by turts121** [comment]
> "Sync Completed" kinda indicates that we've tricked the plugin into thinking it's logged in.
> 
> In settings, turn "Debug Mode" on. Take a look at the console on next sync. You should see the number of tasks the plugin sees....

So after refreshing the browser and forcing a sync again I now see the various tasks in TickTick browser. I tried reading the console but couldn't really figure out which number I was looking for. But it appears the "tricking" worked. However, each time a task is added or I change to a new note the poppup saying "Pleas login from settings." still appears. 

As well, I decided to test something else to my detriment. I uninstalled the plugin to see if a new install would correct the token login issue. It did not. But, the `<vault>\.obsidian\plugins\TickTickSync` folder now no-longer exists, so the option to manually input the token is no longer possible. I imagine this folder and contents gets created on the initial login which is of course now not possible. That means any new user installing this plugin will be locked out completely.

**Comment by thesamim** [comment]
@badralbanna , @programgames , @johnyoonh , @ms3056 : 

BLUF: Please download and test with this version of the plugin:
[TickTickSync-ForTestOnly--1_0_36.zip](https://github.com/user-attachments/files/17440868/TickTickSync-ForTestOnly--1_0_36.zip)

Here's what I'm working with:

1. x-device header is only required on login
2. the "version" number in x-device refers to some internal version of the ticktick api so has to be hard coded not random.
3. I was not diligent enough in testing all possibilities, but it *appears* that version numbers prior to the current version number are accepted. While version numbers greater than the current version cause issues. So generating random numbers for this was a bad idea.
4. The "id" number in x-device refers to a unique identifier for the connected device. I know when going to the signin link from a browser that "id" gets stored in localStorage. I believe this is happening in one of the called scripts. I did not spend time to figure out how to reverse engineer that or get to that "id". But it appears that so long as the id starts with "66", is 24 characters long that it is accepted. In order not to flood ticktick with a million generated random number IDs, I'm now saving that in Obsidian localStorage so that the "id" will be the same on every restart of Obsidian rather than being regenerated every time. 
5. I am not sure what this is going to do with Synching. I'm assuming each device will have it's on "id".  There is clearly the possibility of multiple users accidentally getting the same "id", I haven't addressed that. I need to figure out how to detect the issue and regenerate the "id". IF these changes do not result in a bunch of 469 errors, then that would be a good indicator....
6. In addition to all of the above, it *appears* that ticktick is now checking other cookies that are being sent from the site. (which makes sense, but hasn't been an issue until now.) changed the code to do the right thing with the cookies.

I've tested the scenarios I can think of. But clearly I'm missing some scenarios to test otherwise we wouldn't be here. So I would appreciate your help in testing this out.

Please let me know how things go. Given past results, I will wait at least 48 hours before making another release because we've seen that things change overnight....

Your patience through this discovery journey is much appreciated.

**Comment by thesamim** [comment]
> As well, I decided to test something else to my detriment. I uninstalled the plugin to see if a new install would correct the token login issue. It did not. But, the the Token portion of the data.json file is not present now.

If you extract the zip file from https://github.com/thesamim/TickTickSync/issues/179#issuecomment-2423273034 into your plugins directory and restart Obsidian, it will show up in your community plugins in settings, and then you can just enable it. If you get an error about data.json, disable the plugin and enable it again. From there you will be able to login and start over....

**Comment by badralbanna** [comment]
OK I added the patch, relogged in and things seem to be working for now. 🤞🏼

**Comment by thesamim** [comment]
@badralbanna , @programgames , @johnyoonh , @ms3056 :
Please update to 1.0.37. Please open a new issue for any problems.

Thanks for your support!

**Comment by badralbanna** [comment]
Done! thanks you all your work to keep the plugin working!
