### ISSUE TITLE
it kept adding #ticktick tag to tasks which lead to 86000+ tags added to only  260 tasks. 

### ISSUE THREAD

**Issue by parthvzala** [thesamim/TickTickSync#182]
**Describe the bug**
I selected full vault sync and it started processing. It was still processing after almost 18 hours, and continuously showing a notification stating "New task will be added on the next sync.". 
Obsidian was lagging to open a file that has a filter to show all the tasks in the vault. I noticed `#ticktick` tag was applied to old completed tasks, thousands of times. 
![image](https://github.com/user-attachments/assets/ec68badb-31a2-49b9-a47d-0b868ed891ae)

![image](https://github.com/user-attachments/assets/8e0cb2e8-7aea-4f02-82ed-80935f350b94)

**To Reproduce**
Not sure, but this is what I did. 
1. Tried to login using username and password which failed with 429 error code. 
2. Used cookie token to login. 
3. Started sync.
4. That showed error stating project inbox not found. 
5. changed the location in vault where plugin will save tasks from ticktick but didn't use "+" button so it went back to using root of vault to store files. 
6. Started sync after 5 and did it multiple times until I realized I have to press button next to the text box to apply change. 
7. Change path successfully using the button and started sync. 
8. Changed Project/List where this plugin will push all the tasks on ticktick. 
9. Changed it twice. 

I was just trying to run it to understand how it works and how well it works. I use github to sync so I had no trouble restoring the files but for someone using cloud storage this will be almost impossible to fix or really time consuming to fix. 

**Expected behavior**
1. Tag added only one time to a task. 
2. There should be an option to turn off tags and or what tag to use. 

**Screenshots**
Added above. 

**Set up questions:
- Is this your first time using TickTickSycn?
Yes

- Is your Vault shared across devices?
No

- Do you have a Default Folder Location?
I set that in the plugin but check the reproduce section for more. 

- Do you have "Full Vault Sync" enabled?
Yes

- Do you have "Debug Mode" enabled?
No. I tried at the end but Obsidian lagging so much I kill the app and opened again. Not sure debug was active than or not. 

- Do you have either of the "Limit Synchronization" settings set?
Yes, a folder on ticktick selected. 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Brave
 - Version Latest from yesterday. 

**Smartphone (please complete the following information):**
- Not used.

**Comment by thesamim** [comment]
I'm so sorry. This was an old bug, and I thought it was fixed. I'll debug once we're past the 429 errors....

In the mean time, if this messed up your ticktick, there should be a back up file in the root of your vault folder. To check to make sure it's as you expect it, but you should be able to delete tasks in ticktick and import from the CSV.

**Comment by thesamim** [comment]
@parthvzala : I've just retested full vault sync. And reproduced your conditions, namely: limiting tasks to a folder AND enabling full vault sync. It's all working as expected. Meaning that all tasks in any file in that folder were added correctly. Did not see the repetition of the ticktick as you did.

Please start over, paying attention to click the + sign when changing the folder and retest. Let me know what happens.

**Comment by parthvzala** [comment]
@thesamim Hey thanks for the quick response. Sorry Today only I saw your answered already. 

Also, no need to be sorry, 😀. I am still happy that something like this is available. 

I will try again and update you in coming days. I use git so it was easy for me to fix this anyways.

**Comment by thesamim** [comment]
@parthvzala : Assuming that since I haven't heard back from you, the issue has not reoccurred. Though I still want to understand how it happened, I'm going to close this issue. If it happens again, please reopen or open a new issue.
