### ISSUE TITLE
Login Failed (error 500)

### ISSUE THREAD

**Issue by gyuraam** [thesamim/TickTickSync#184]
**PS. I'm using a translator. The choice of words can be unnatural.**

**Describe the bug**
I can't login. An error message appears. Have tried changing my password twice and I still get a message.

**To Reproduce**
1. Go to TickTickSync settings & entered username and password.
2. Click on login
3. See error

**Expected behavior**
I want to login.

**Screenshots**
![image](https://github.com/user-attachments/assets/5443d245-43d8-4e64-9af2-ff6745e77332)

console
![image](https://github.com/user-attachments/assets/758430d9-2bbb-441a-b792-f1316b5c4ae6)
![image](https://github.com/user-attachments/assets/261c1a4f-afcc-4717-81d9-9292435ddbd9)

**Set up questions:
- Is this your first time using TickTickSycn? No
- Is your Vault shared across devices? Yes
  - If it is: What Vault synchronization method are you using (eg: Obsidan Sync, Syncthing...)? google drive(PC)
- Do you have a Default Folder Location? No
- Do you have a Default project? No
- Do you have "Full Vault Sync" enabled? No
- Do you have "Debug Mode" enabled? Yes
- Do you have either of the "Limit Synchronization" settings set? 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  Windows 11
 - Browser [e.g. chrome, safari] chrome

**Smartphone (please complete the following information):**

**Additional context**
I am using version TickTickSync 1.037.

**Comment by thesamim** [comment]
@gyuraam 
It appears that the previous version of TickTickSync has left a bad ID behind: 
![image](https://github.com/user-attachments/assets/02a2d914-3647-4ead-ab58-b984b3281ec9)

Let's Please try this:
Disable TickTickSync from community plugin settings.

In the console, please paste this code and run it. 
```
Object.keys(localStorage)
      .forEach(function(key){
           if (/TTS_.*/.test(key)) {
               localStorage.removeItem(key);
           }
       });
```
(**NOTE**: It is never a good idea to run code that someone tells you to run in your console if you don't know what the code is doing. This code is removing the old saved data that TickTickSync left behind. The intent is to start with clean IDs.)

Enable TickTickSync from community plugin settings.

Try logging in again. 

Let me know what happens.

**Comment by gyuraam** [comment]
Thank you!
I've logged on.

**Comment by thesamim** [comment]
> However, the schedule created by TikTik is not synchronized to Obsidian.

If that is still a problem, please let me have your console log so I can see what's going on.

**Comment by gyuraam** [comment]
![image](https://github.com/user-attachments/assets/c6b2b1c1-e66f-4ad5-98a8-241af8230629)
This is my console log.

**Comment by thesamim** [comment]
@gyuraam 

Please try this:

In the `<vault>\.obsidian\plugins\TickTickSync\data.json file`
change: 
` "checkPoint": 1356998400000, `   //(Current number not important
to 
` "checkPoint": 1727553846,` 

Explanation: 
The checkpoint number is a Unix date. It used to be that a sufficiently old date would bring back all the tasks. TickTick has apparently changed their back end and if the date is too old it will bring nothing back.

**Comment by gyuraam** [comment]
The problem is not resolved.
Continuously, the schedule generated by TikTik is not synchronized with Obsidian.

**Comment by thesamim** [comment]
I have to ask: did you close Obsidian and open it again?

**Comment by thesamim** [comment]
@gyuraam 
Please report further findings in #186
