### ISSUE TITLE
Tasks sync from Obsidian but not to Obsidian

### ISSUE THREAD

**Issue by ArtofGaming** [thesamim/TickTickSync#185]
Tasks created in TickTick do not sync to Obsidian. However it may recognize them in some form as it seems they are added to the cache but just never leave

1. Create task in TickTick
2. Add #ticktick as tag
3. Open Obsidian
4. Tick on debug mode
5. Either wait for auto sync or press manual sync

I expected my TickTick task to appear in the appropriate note in Obsidian

- Is this your first time using TickTickSycn? Yes
- Is your Vault shared across devices? Yes
  - If it is: What Vault synchronization method are you using (eg: Obsidan Sync, Syncthing...)? Google Drive
- Do you have a Default Folder Location? Yes
- Do you have a Default project? Yes
- Do you have "Full Vault Sync" enabled? No
- Do you have "Debug Mode" enabled? Yes
- Do you have either of the "Limit Synchronization" settings set? No

**Comment by thesamim** [comment]
> * Do you have a Default Folder Location? Yes
> 
> * Do you have a Default project? Yes

Do you have a file in the default folder with the default project associated with it?
![image](https://github.com/user-attachments/assets/a66a6ec6-300f-494b-a09c-55695ac9ea4e)

If not, please try that.
If yes. please turn on "Debug Mode" in settings, force a sync, send me the console log.

**Comment by willmanduffy** [comment]
I'm also having a similar issue. I can create tasks in Obsidian and they sync to TickTick perfectly. However, if I create a tasks in TickTick it does not sync back.

Unlike the reporter of this issue I do not see them in the cache.

* Is this your first time using TickTickSycn? Yes
* Is your Vault shared across devices? Yes. Worth noting I am not currently using the other devices because I wanted to get it working simply first
  * If it is: What Vault synchronization method are you using (eg: Obsidan Sync, Syncthing...)? Obsidian Sync.
Do you have a Default Folder Location? Yes
Do you have a Default project? Yes
Do you have "Full Vault Sync" enabled? No
Do you have "Debug Mode" enabled? Yes
Do you have either of the "Limit Synchronization" settings set? No


https://github.com/user-attachments/assets/ab2a6fc2-9e22-4213-ada7-28df7f3bd799

**Comment by thesamim** [comment]
@willmanduffy : you situation might be slightly different.

Please try this:

In the `<vault>\.obsidian\plugins\TickTickSync\data.json file`
change: 
` "checkPoint": 1356998400000, `   //(Current number not important
to 
` "checkPoint": 1727553846,` 

Explanation: 
The checkpoint number is a Unix date. It used to be that a sufficiently old date would bring back all the tasks. TickTick has apparently changed their back end and if the date is too old it will bring nothing back.

1727553846 is: Sat Sep 28 2024 20:04:06 GMT+0000

Hopefully, this will now bring back ALL the TickTick tasks. If it does not, please let me know.

@ArtofGaming : if setting the default project for the file doesn't work, please also try the checkpoint change above.

**Comment by lyovson** [comment]
Got the same issue here, 

> @willmanduffy : you situation might be slightly different.
> 
> Please try this:
> 
> In the `<vault>\.obsidian\plugins\TickTickSync\data.json file` change: `"checkPoint": 1356998400000,` //(Current number not important to ` "checkPoint": 1727553846,`
> 
> Explanation: The checkpoint number is a Unix date. It used to be that a sufficiently old date would bring back all the tasks. TickTick has apparently changed their back end and if the date is too old it will bring nothing back.
> 
> 1727553846 is: Sat Sep 28 2024 20:04:06 GMT+0000
> 
> Hopefully, this will now bring back ALL the TickTick tasks. If it does not, please let me know.
> 
> @ArtofGaming : if setting the default project for the file doesn't work, please also try the checkpoint change above.

Got the same issue, this solution didn't help // 

Is this your first time using TickTickSycn? Yes
Is your Vault shared across devices? Yes. 
If it is: What Vault synchronization method are you using (eg: Obsidan Sync, Syncthing...)? Obsidian Sync.
Do you have a Default Folder Location? Yes 
Do you have a Default project? Yes
Do you have "Full Vault Sync" enabled? No
Do you have "Debug Mode" enabled? Yes
Do you have either of the "Limit Synchronization" settings set? No

**Comment by willmanduffy** [comment]
@thesamim I tried this out and it didn't seem to help. It's worth nothing that after the first sync it instantly changed to 1356998400000 again. 

Let me know if creating a separate would be helpful!

**Comment by thesamim** [comment]
@willmanduffy , @ArtofGaming :

Please report further findings in #186
