### ISSUE TITLE
Tasks fetch failing.

### ISSUE THREAD

**Issue by thesamim** [thesamim/TickTickSync#186]
Consolidating into one issue.

Please check your consoles and let me know if you see lines similar to:
```
Attempted Checkpoint:  1727380477790
VM255126 plugin:tickticksync:14158 Check point has been changed. 1727380477790
```
And what those numbers are.

**Comment by willmanduffy** [comment]
@thesamim I don't have any output like that. I don't see "Attempted Checkpoint" anywhere in the codebase. Where does it come from?

**Comment by ArtofGaming** [comment]
I'm also not seeing that in my console. I do however now get an error upon syncing:
`plugin:tickticksync:14131 Get Inbox Properties TypeError: Cannot read properties of null (reading 'update')
    at Tick.getInboxProperties (plugin:tickticksync:13657:36)
    at async TickTickRestAPI.initializeAPI (plugin:tickticksync:14269:11)
    at async TickTickSync.initializePlugin (plugin:tickticksync:24878:5)
    at async TickTickSync.onload (plugin:tickticksync:24681:7)`

**Comment by LemurTech** [comment]
Hello @thesamim! 

Task fetch/sync is failing for me, as well. In my case, the login appears to work just fine. I don't have any 'checkpoint' issues displayed. But tasks are not being syced either way. Console shows that TickTick API isn't returning any tasks!

```TickTick scheduled synchronization task started at 10/28/2024, 9:00:41 AM
plugin:tickticksync:24376 We have:  0  tasks on https://api.ticktick.com/api/v2
plugin:tickticksync:24379 openTasks 0 closedTasks 0
plugin:tickticksync:24384 There are:  471  tasks in Cache.
plugin:tickticksync:24467 No synchronization changes.```

I've had this issue for a few days now. Apologies if this is a different issue. But then, how often do these things turn out to be some rando TickTick API change...

**Comment by thesamim** [comment]
@willmanduffy @LemurTech @ArtofGaming :

I **Think** I know what's going on. TL;DR I made the last checkpoint processing changes in the wrong `<dirtyword/>` place.

Could you please:
1. Close Obsidian
2. Back up your plugin directory
3. Extract the attached into  your plugin directory
4. Restart  Obsidian
5. Let me know what happens.

Thanks for your patience.

[TickTickSync-ForTestOnly--1_0_38.zip](https://github.com/user-attachments/files/17547677/TickTickSync-ForTestOnly--1_0_38.zip)

**Comment by willmanduffy** [comment]
@thesamim That seemed to have done the trick for me!

**Comment by LemurTech** [comment]
That did it! Cheers!

```
TickTick scheduled synchronization task started at 10/28/2024, 12:23:35 PM
plugin:tickticksync:14158 Check point has been changed. 1728847415375
getPreviousCheckPoint @ plugin:tickticksync:14158
getTaskDetails @ plugin:tickticksync:13757
await in getTaskDetails (async)
getAllTasks @ plugin:tickticksync:14515
await in getAllTasks (async)
syncTickTickToObsidian @ plugin:tickticksync:24345
await in syncTickTickToObsidian (async)
scheduledSynchronization @ plugin:tickticksync:25083
await in scheduledSynchronization (async)
eval @ plugin:tickticksync:24708
plugin:tickticksync:24397 We have:  115  tasks on https://api.ticktick.com/api/v2
plugin:tickticksync:24400 openTasks 45 closedTasks 70
plugin:tickticksync:24405 There are:  471  tasks in Cache.
plugin:tickticksync:23186 === (6) [{…}, {…}, {…}, {…}, {…}, {…}]0: {id: '671bd003e5ccf720e6a35044', projectId: '65d7ae4b8f0863df68630fbd', sortOrder: 288072588853343, title: 'ADP Timecard Due [Task Sync/Work.md](obsidian://open?vault=Public&file=Task%20Sync/Work.md)', content: '', …}1: {id: '671bcdbc8f08d2138afb357e', projectId: '65d7ae4b8f0863df68630fbd', sortOrder: 297975441391711, title: '[jira] JIRA:INFRA-12202 Document Key Concepts and …ian://open?vault=Public&file=Task%20Sync/Work.md)', content: 'Document Key Concepts and Steps to Deploy LAPS\r\n\r\n…en domain trust\r\n ** Offline domain controllers\r\n', …}2: {id: '671a71f08f08d2138abd29c0', projectId: '65d7ae4b8f0863df68630fbd', sortOrder: 299074953019487, title: '[jira] JIRA:INFRA-12099 APM Group to Dynamic [Task…ian://open?vault=Public&file=Task%20Sync/Work.md)', content: "APM Group to Dynamic\n\nKey: INFRA-12099\nURL: https:…tive role called out in the groups' name schema.\n", …}3: {id: '671952de8f08d2138a89cff1', projectId: '65d7ae4b8f0863df68630fbd', sortOrder: 300174464647263, title: '[jira] JIRA:INFRA-12164 TESTGRAPPA - Developer Sha…ian://open?vault=Public&file=Task%20Sync/Work.md)', content: 'TESTGRAPPA - Developer Shares: roguenet-branden, r…shares; this has been prepped the previous week.\n', …}4: {id: '67192b338f08d2138a81fa59', projectId: '65d7ae4b8f0863df68630fbd', sortOrder: 301273976275039, title: '[jira] JIRA:INFRA-12160 Remove extraneous NTFS per…ian://open?vault=Public&file=Task%20Sync/Work.md)', content: 'Remove extraneous NTFS permissions on recently-dis… disabled shares whose NTFS folders need review.\n', …}5: {id: '671be2548f08d2138affa3b1', projectId: '65d7ae4b8f0863df68630fbd', sortOrder: 302373487902815, title: '[jira] JIRA:ICM-6325 Remove Prologue-related Share…ian://open?vault=Public&file=Task%20Sync/Work.md)', content: 'Matthew Arciniega has just updated this issue\r\n\r\nI…etainf.jira.plugin.emailissue/server/overview].\r\n', …}length: 6[[Prototype]]: Array(0) Completed add task.
plugin:tickticksync:24488 File System Modified.
plugin:tickticksync:25086 TickTick scheduled synchronization task completed at 10/28/2024, 12:23:43 PM
```

**Comment by ArtofGaming** [comment]
That worked for me as well! Thank you so much!

**Comment by gyuraam** [comment]
@thesamim 

Still not syncing from TikTik to Obsidian. I tried logging in again.
![image](https://github.com/user-attachments/assets/55220a12-995d-4f8d-8d20-a18520260b0b)
Now I can't even log in.

This is my console record.

`'generatedID':  66b733eef88c3ee6ba704ff3
plugin:tickticksync:13621 Signed in Response:  {token: '154BB8FE914467832EA8B76C0BCA597C693FDB6B157A19F602…0E2D32D062BAC5AF358405ECCA2B1AE9821B10617E99B771F', userId: '124327982', userCode: 'f392e4f01d0b46c181a1a733370877ff', username: 'raam921@gmail.com', teamPro: false, …}
plugin:tickticksync:13671 Get Inbox Properties failed:  TypeError: Cannot read properties of null (reading 'update')
    at Tick.getInboxProperties (plugin:tickticksync:13655:36)
    at async Tick.login (plugin:tickticksync:13625:15)
    at async eval (plugin:tickticksync:14649:28)
getInboxProperties @ plugin:tickticksync:13671
await in getInboxProperties (async)
login @ plugin:tickticksync:13625
await in login (async)
eval @ plugin:tickticksync:14649
(anonymous) @ app.js:1
plugin:tickticksync:14143 Get Inbox Properties TypeError: Cannot read properties of null (reading 'update')
    at Tick.getInboxProperties (plugin:tickticksync:13655:36)
    at async Tick.login (plugin:tickticksync:13625:15)
    at async eval (plugin:tickticksync:14649:28)
setError @ plugin:tickticksync:14143
getInboxProperties @ plugin:tickticksync:13672
await in getInboxProperties (async)
login @ plugin:tickticksync:13625
await in login (async)
eval @ plugin:tickticksync:14649
(anonymous) @ app.js:1
plugin:tickticksync:14672 Last Error:  {operation: 'Get Inbox Properties', statusCode: 666, errorMessage: TypeError: Cannot read properties of null (reading 'update')
    at Tick.getInboxProperties (plugin…}errorMessage: TypeError: Cannot read properties of null (reading 'update')
    at Tick.getInboxProperties (plugin:tickticksync:13655:36)
    at async Tick.login (plugin:tickticksync:13625:15)
    at async eval (plugin:tickticksync:14649:28)operation: "Get Inbox Properties"statusCode: 666[[Prototype]]: Object`

**Comment by thesamim** [comment]
Have you upgraded to 1.0.38?

**Comment by gyuraam** [comment]
> @gyuraam :
> 
> Have you upgraded to 1.0.38?

Yes. I upgraded to version 1.0.38.

**Comment by thesamim** [comment]
> > @gyuraam :
> > Have you upgraded to 1.0.38?
> 
> Yes. I upgraded to version 1.0.38.

Have you tried uninstalling and re-installing the plugin?

**Comment by gyuraam** [comment]
> > > @gyuraam :
> > > Have you upgraded to 1.0.38?
> > 
> > 
> > Yes. I upgraded to version 1.0.38.
> 
> Have you tried uninstalling and re-installing the plugin?


It's finally starting to work!
I'm happy!
Thank you!

**Comment by NaturallyAsh** [comment]
Hello, I am experiencing the same issue of changes I make in TickTick not updating Obsidian while changes I make in Obsidian updates tasks in TickTick. Plugin is updated to 1.0.39. I also tried adding the test zip file you posted, but that didn't work and I reverted back. I'm not using any limits. I have a default folder and default project. When I force Sync, it's showing `We have:  0  tasks on https://api.ticktick.com/api/v2` and 35 tasks in cache. No errors.

**Comment by NaturallyAsh** [comment]
Nevermind! This issue for me is also resolved. Thanks.

**Comment by thesamim** [comment]
@NaturallyAsh 

> Nevermind! This issue for me is also resolved. Thanks.
Glad to hear it.

Did you do anything, or did suddenly start working?

**Comment by NaturallyAsh** [comment]
> @NaturallyAsh
> 
> > Nevermind! This issue for me is also resolved. Thanks.
> > Glad to hear it.
> 
> Did you do anything, or did suddenly start working?

I thought I had version 1.0.39 but I had 1.0.39. After updating to the latest version, changes in TickTick began reflecting in Obsidian after pressing "Sync" or after the sync interval.
