### ISSUE TITLE
The description of the tasks are not synced

### ISSUE THREAD

**Issue by jarodise** [thesamim/TickTickSync#189]
**Describe the bug**
I recently just installed the plugin and ran some tests, it seems to me that when adding a task, the descriptions part of the tasks are not synced by default, only the title part is shown in the synced md file, not sure this is a bug or designed that way. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Set up questions:
- Is this your first time using TickTickSycn?
- Is your Vault shared across devices?
  - If it is: What Vault synchronization method are you using (eg: Obsidan Sync, Syncthing...)? 
- Do you have a Default Folder Location?
- Do you have a Default project?
- Do you have "Full Vault Sync" enabled?
- Do you have "Debug Mode" enabled?
- Do you have either of the "Limit Synchronization" settings set?

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thesamim** [comment]
It is designed this way, but: 

1. If you have a checklist in the description/notes that checklist will be synced. A temporary work around would be to make your descriptions checklists.
2. Please watch #168 It is an often requested feature and I will be working on it soon.

**Comment by thesamim** [comment]
@jarodise : Closing this. #168 should ought to take care of the concern.
