### ISSUE TITLE
TickTick completed task not updated to Obsidian

### ISSUE THREAD

**Issue by unwan878** [thesamim/TickTickSync#19]
Q: Was the task in the Inbox, or in a list?
A: inbox

Q: Does this happen all the time, or just in on some tasks?
A: Happened all the time

Q: How long did you wait before the manual sync?
A: 1 hour, I put it there for few hours

Q: Does waiting for the scheduled sync make a diffference?
A: Nope, I have tried wait for the scheduled sync (20sec and 5mins)

Q: If you mark a task done in TickTick, then mark as open, then mark it as done again, what do you see?
A: Does not update the "done" in Obsidian

When I completed a task in Obsidian, it marks as done at TickTick, but when I reverse the process which I mark the task as completed at TickTick, it won't update to Obsidian, even though I have manually click on sync.

![image](https://github.com/thesamim/TickTickSync/assets/81401809/57bfa945-8ef2-4673-bc8d-b0a78d428b62)
![image](https://github.com/thesamim/TickTickSync/assets/81401809/77400e00-e321-40c7-b1b9-550a3ca86356)

**Comment by thesamim** [comment]
@unwan878 : Could you please re-test with latest release?
