### ISSUE TITLE
Login not possible 

### ISSUE THREAD

**Issue by tinberworld** [thesamim/TickTickSync#190]
I am not able to Login via Access Control to TickTickSync. I am able to access ticktick via browser with my credentials - I already chnage the Password - I have no Idea whats wrong

Ich would be happy to get some help please

Login failed
"operation":"Login"
“statusCode":500
"errorMessage":
"errorId":"hzt5xnjd@tw10"
"errorCode":"username_password_not_match"
"errorMessage": MYEMAILADRESS
"data":null

**Comment by thesamim** [comment]
have you used the plugin before?
have you been able to login  before?
which version of the plugin are you using?
Have you tried uninstalling and re-installing it?

**Comment by tinberworld** [comment]
Hi thesamin
Yes i am using the Plugin already for quite some Time very sucessfully and could Login without any Problem 
After my holydays the issue came up
I deleted and reinstalled tickticksync
The Version is Obsidian v1.75 tickticksync v1.0.38

just tried another reinstall - still cannot Login

**Comment by thesamim** [comment]
Please try the checkpoint change instructions here: https://github.com/thesamim/TickTickSync/issues/185#issuecomment-2441870050

**Comment by tinberworld** [comment]
Sorry still not working - same Message - only change in 
"errorId":"dbrf2fvy@tw11"

**Comment by thesamim** [comment]
Please send me your console log showing the whole login process.

**Comment by tinberworld** [comment]
Am Di., 12. Nov. 2024 um 16:03 Uhr schrieb thesamim <
***@***.***>:

**Comment by tinberworld** [comment]
[obsidian.md-1731430368164.log](https://github.com/user-attachments/files/17720142/obsidian.md-1731430368164.log)

**Comment by thesamim** [comment]
@tinberworld:

1. I deleted your reply from the thread because it contains your email address, but thank you for sending.
2. Please try this; https://github.com/thesamim/TickTickSync/issues/184#issuecomment-2439722199
3. If that doesn't work: Sorry, I should have asked for this before: Please turn on "Debug Mode" in settings and then send me your log again.

**Comment by tinberworld** [comment]
How do I turn on debug mode?

Am Di., 12. Nov. 2024 um 18:28 Uhr schrieb thesamim <
***@***.***>:

**Comment by tinberworld** [comment]
#184 didnot help - but I had no debug mode

Am Di., 12. Nov. 2024 um 18:40 Uhr schrieb Tina Weisser <
***@***.***>:

**Comment by thesamim** [comment]
Please try the checkpoint change instructions here: https://github.com/thesamim/TickTickSync/issues/185#issuecomment-2441870050

**Comment by thesamim** [comment]
To turn on debug mode, go to TickTickSync plugin settings, go to the bottom, under Manual Operations you will see "Debug mode".....

**Comment by tinberworld** [comment]
no does not work: debug on , changed "checkPoint": 1727553846[obsidian.md-1731439426152.log](https://github.com/user-attachments/files/17721692/obsidian.md-1731439426152.log)

**Comment by thesamim** [comment]
for some reason, not seeing the debug logs in the attached. 

Please check your checkpoint value to: 1730437200000

Please double check that you do have Debug turned on.

Please restart Obsidian after changing the checkpoint and double checking that Debug is turned on.

Thanks for your patience.

**Comment by tinberworld** [comment]
I will try again tomorrow 

on iPhone I receive a different error
![IMG_5021](https://github.com/user-attachments/assets/829a611c-e371-497e-9730-a14b5bec8306)

**Comment by thesamim** [comment]
That's interesting. This is indicating that you got past login (somehow) on iPhone, but the next call to TickTick failed to get the inbox properties and Ticktick didn't tell us the reason for the failure. 

I'd strongly recommend getting desktop working first. Then synchronizing. Then trying again on iPhone.

**Comment by tinberworld** [comment]
changed json, Debug was on, restarted obsidian - also thanks for your patience
[obsidian.md-1731445502246.log](https://github.com/user-attachments/files/17722807/obsidian.md-1731445502246.log)
<img width="295" alt="Bildschirmfoto 2024-11-12 um 22 06 35" src="https://github.com/user-attachments/assets/c513111b-d4f3-48c7-8720-168fd24694bf">
<img width="685" alt="Bildschirmfoto 2024-11-12 um 22 05 39" src="https://github.com/user-attachments/assets/e80e476e-38d9-474e-9646-17e2f75ec6d3">

**Comment by thesamim** [comment]
That's interesting. This is indicating that you got past login (somehow) on iPhone, but the next call to TickTick failed to get the inbox properties and Ticktick didn't tell us the reason for the failure. 

I'd strongly recommend getting desktop working first. Then synchronizing. Then trying again on iPhone.

**Comment by thesamim** [comment]
@tinberworld 
> plugin:tickticksync:14172 'generatedID':  c983b51c-0c0f-419c-97df-680b703156a2
This is still a problem.

could you please try this again: https://github.com/thesamim/TickTickSync/issues/184#issuecomment-2439722199

The restart Obsidian and let me know what happens.

Thanks.

**Comment by tinberworld** [comment]
same story again  sorry
[obsidian.md-1731511799730.log](https://github.com/user-attachments/files/17734997/obsidian.md-1731511799730.log)
[obsidian.md-1731511859568.log](https://github.com/user-attachments/files/17734998/obsidian.md-1731511859568.log)

**Comment by thesamim** [comment]
ok, let's try this: 

Please unzip the attached, and copy main.js to `<vault folder>\.obsidian\plugins\tickticksync`

Restart Obsidian and login again.

The only change is that TickTickSync will now detect the bad unique id and generate a new one.

[TTS-Main-1.0.38.zip](https://github.com/user-attachments/files/17735402/TTS-Main-1.0.38.zip)

**Comment by tinberworld** [comment]
Its running - thanks a lot for your patience and help
;) tinberworld
