### ISSUE TITLE
Unable to login.. error code "666"

### ISSUE THREAD

**Issue by zuwf** [thesamim/TickTickSync#195]
![Screenshot_2024-11-17-12-38-56-594_md.obsidian-edit.jpg](https://github.com/user-attachments/assets/fbe4d864-a505-49d0-b2fc-7682dd8c7796)

Using recent version updated 2 days back

And this is the only plugin installed in my vault

**Comment by thesamim** [comment]
@zuwf : Please try this: https://github.com/thesamim/TickTickSync/wiki/Resetting-Checkpoint

**Comment by thesamim** [comment]
@zuwf : Being that I haven't heard from you, I'm assuming that this is fixed. If it's not, please reopen.
