### ISSUE TITLE
Completed date is changed when syncing

### ISSUE THREAD

**Issue by ajvalenc** [thesamim/TickTickSync#196]
**Describe the bug**
The completed date is changed to the current date for tasks marked as completed. I like to use TickTick's completed date option to track the history of my work done in the past. However, when syncing with Obsidian the completed date for all my tasks is changed to the current date, so essentially they all appear as if they were completed on the date they were synced.

**Expected behavior**
Completed date shouldn't changed when syncing.

**Desktop (please complete the following information):**
 - OS: MacOS
<img width="865" alt="Screenshot 2024-11-20 at 1 42 21 PM" src="https://github.com/user-attachments/assets/450a2f33-d9fd-4bbd-a021-e4eafc4761e2">

**Comment by thesamim** [comment]
@ajvalenc : Do you mean: when you complete the task from TickTick, or when you complete the task from Obsidian? Or Both?

**Comment by zx900930** [comment]
I have the same issue:
step to reproduce:
1. create a new project in ticktick
2. sync that project to obsidian
3. paste tasks written in Tasks Emoji Format for Dates, for example:  `- [x] example task.  #ticktick ➕ 2024-11-27 🛫 2024-11-27 📅 2024-11-27 ✅ 2024-11-27`
4. sync obsidian -> ticktick
5. after sync the done date in ticktick is corrent, but the finish date changed to current date. `- [x] example task.  #ticktick ➕ 2024-11-27 🛫 2024-11-27 📅 2024-11-27 ✅ 2024-11-29`

**Comment by thesamim** [comment]
@zx900930 : Thanks for the clarification.

@ajvalenc, @zx900930 : Please see https://github.com/thesamim/TickTickSync/issues/97#issuecomment-2506618167 I've made the change there. It's not released yet, but if you are able to test from that Zip file, that would be awesome.
