### ISSUE TITLE
Bug - Tasks do not get updated from Obsidian mobile - Fix suggested

### ISSUE THREAD

**Issue by coneos** [thesamim/TickTickSync#202]
If I create a task in my daily note with #project1 it will correctly add it also to the synced folder project1 which will sync with the project1 list on TT but if I change task details on TT it will only update the synced folder task and not the daily note task.
Awesome plugin by the way, thank you! =)

**Comment by coneos** [comment]
My bad it is actually working as expected/hoped on windows.
My vault is on a google drive which is synced to android with FolderSync, the issue happens only on mobile and here is the console logs : 

Error adding task: TypeError: Cannot read properties of undefined (reading 'createHash')
    at TaskParser.getLineHash (plugin:tickticksync:5723:26)
    at SyncMan.addTask (plugin:tickticksync:7144:52)
    at async SyncMan.lineContentNewTaskCheck (plugin:tickticksync:7121:5)
    at async eval (plugin:tickticksync:8526:9)
addTask @ plugin:tickticksync:7148
await in addTask
lineContentNewTaskCheck @ plugin:tickticksync:7121
eval @ plugin:tickticksync:8526
await in eval
e.tryTrigger @ app.js:1
e.trigger @ app.js:1
t.trigger @ app.js:1
t.onUpdate @ app.js:1
t.onUpdate @ app.js:1
(anonymous) @ app.js:1
e.update @ app.js:1
dispatchTransactions @ app.js:1
e.dispatch @ app.js:1
t.transaction @ app.js:1
t.selectSuggestion @ app.js:1
e.useSelectedItem @ app.js:1
e.onSuggestionClick @ app.js:1
s @ enhance.js:1
plugin:tickticksync:7149 The error occurred in file: Untitled 1.md
addTask @ plugin:tickticksync:7149
await in addTask
lineContentNewTaskCheck @ plugin:tickticksync:7121
eval @ plugin:tickticksync:8526
await in eval
e.tryTrigger @ app.js:1
e.trigger @ app.js:1
t.trigger @ app.js:1
t.onUpdate @ app.js:1
t.onUpdate @ app.js:1
(anonymous) @ app.js:1
e.update @ app.js:1
dispatchTransactions @ app.js:1
e.dispatch @ app.js:1
t.transaction @ app.js:1
t.selectSuggestion @ app.js:1
e.useSelectedItem @ app.js:1
e.onSuggestionClick @ app.js:1
s @ enhance.js:1
plugin:tickticksync:8818 TickTick scheduled synchronization task started at 22/12/2024, 6:39:54 p.m.
plugin:tickticksync:6012 File path not found for 67689f3047f0284498f17521, returning mylist.md instead. 
getFilepathForProjectId @ plugin:tickticksync:6012
await in getFilepathForProjectId
addTasksToFile @ plugin:tickticksync:6538
syncTickTickToObsidian @ plugin:tickticksync:7816
await in syncTickTickToObsidian
scheduledSynchronization @ plugin:tickticksync:8825
await in scheduledSynchronization
eval @ plugin:tickticksync:8594
plugin:tickticksync:6566 Creating new file: Tasks/TickTick/mylist.md
getOrCreateDefaultFile @ plugin:tickticksync:6566
addTasksToFile @ plugin:tickticksync:6543
await in addTasksToFile
syncTickTickToObsidian @ plugin:tickticksync:7816
await in syncTickTickToObsidian
scheduledSynchronization @ plugin:tickticksync:8825
await in scheduledSynchronization
eval @ plugin:tickticksync:8594
plugin:tickticksync:6572 File creation failed:  Error: File already exists.
    at t.<anonymous> (app.js:1:750027)
    at app.js:1:237226
    at Object.next (app.js:1:237331)
    at a (app.js:1:236049)
getOrCreateDefaultFile @ plugin:tickticksync:6572
await in getOrCreateDefaultFile
addTasksToFile @ plugin:tickticksync:6543
await in addTasksToFile
syncTickTickToObsidian @ plugin:tickticksync:7816
await in syncTickTickToObsidian
scheduledSynchronization @ plugin:tickticksync:8825
await in scheduledSynchronization
eval @ plugin:tickticksync:8594
plugin:tickticksync:6574 Attempting to find existing file
getOrCreateDefaultFile @ plugin:tickticksync:6574
await in getOrCreateDefaultFile
addTasksToFile @ plugin:tickticksync:6543
await in addTasksToFile
syncTickTickToObsidian @ plugin:tickticksync:7816
await in syncTickTickToObsidian
scheduledSynchronization @ plugin:tickticksync:8825
await in scheduledSynchronization
eval @ plugin:tickticksync:8594
plugin:tickticksync:8828 TickTick scheduled synchronization task completed at 22/12/2024, 6:40:01 p.m.

**Comment by coneos** [comment]
I guess the issue on android is related to authentication because I could never log in directly from my phone as I was getting the error 666 and your workaround suggested below did not work : 

https://github.com/thesamim/TickTickSync/wiki/Resetting-Checkpoint

plugin:tickticksync:4201 Login SyntaxError: Unexpected token '', "�"... is not valid JSON
    at JSON.parse (<anonymous>)
    at get json (app.js:1:1942603)
    at Tick.makeRequest (plugin:tickticksync:4119:21)
    at async Tick.login (plugin:tickticksync:3678:24)
    at async eval (plugin:tickticksync:4714:28)
plugin:tickticksync:4122 SyntaxError: Unexpected token '', "�"... is not valid JSON
    at JSON.parse (<anonymous>)
    at get json (app.js:1:1942603)
    at Tick.makeRequest (plugin:tickticksync:4119:21)
    at async Tick.login (plugin:tickticksync:3678:24)
    at async eval (plugin:tickticksync:4714:28)
plugin:tickticksync:3679 Signed in Response:  null
plugin:tickticksync:4737 Last Error:  
{operation: 'Login', statusCode: 666, errorMessage: SyntaxError: Unexpected token '', "�"... is not valid JSON
    at JSON.parse (<anonymous>…}
errorMessage
: 
SyntaxError: Unexpected token '', "�"... is not valid JSON at JSON.parse (<anonymous>) at get json (http://localhost/app.js:1:1942603) at Tick.makeRequest (plugin:tickticksync:4119:21) at async Tick.login (plugin:tickticksync:3678:24) at async eval (plugin:tickticksync:4714:28)
operation
: 
"Login"
statusCode
: 
666
[[Prototype]]
: 
Object


When I logged in from desktop then it would allow to log in from android with the synced vault.

I guess the errors below when trying to update tasks from android are also related. Creating tasks from obsidian or retrieving new ones from TT works perfectly though pn android, just not updating obsidian tasks :

3plugin:tickticksync:7615 Error modifying task: TypeError: Cannot read properties of undefined (reading 'createHash')
    at TaskParser.getLineHash (plugin:tickticksync:5723:26)
    at SyncMan.lineModifiedTaskCheck (plugin:tickticksync:7231:47)
    at SyncMan.fullTextModifiedTaskCheck (plugin:tickticksync:7612:24)
    at async TickTickSync.scheduledSynchronization (plugin:tickticksync:8915:11)
    at async eval (plugin:tickticksync:8594:58)

**Comment by thesamim** [comment]
> plugin:tickticksync:4201 Login SyntaxError: Unexpected token '�', "���"... is not valid JSON

This is actually the issue.

For some reason the response from TickTick has invalid characters in the JSON response. Which is causing the exception. This is the first time I've seen this reported. 

Questions:

1. On Android, are you using a VPN or anything that might be "interpreting" the network response?
2. are you using a non-latin language on Android or on TickTick? (Highly unlikely that that's the issue.)
3. Have you tried loging in again since the original issue? (Might have been a temporary glitch on the TickTick side.)
4. Is there anything non-standard about the way you connect to the internet?

**Comment by coneos** [comment]
I think there are 2 bugs unless they are related.
First is the login error with response 666, I have tried on another android phone with new install of obsidian and only your plugin installed. They are both using Español (América) as language, i will try to change it and see. 
The more annoying is not being able to update a task from obsidian android and it i seems to be related to the second error that is appearing at that moment:
3plugin:tickticksync:7615 Error modifying task: TypeError: Cannot read properties of undefined (reading 'createHash')
at TaskParser.getLineHash (plugin:tickticksync:5723:26)
at SyncMan.lineModifiedTaskCheck (plugin:tickticksync:7231:47)
at SyncMan.fullTextModifiedTaskCheck (plugin:tickticksync:7612:24)
at async TickTickSync.scheduledSynchronization (plugin:tickticksync:8915:11)
at async eval (plugin:tickticksync:8594:58)

**Comment by coneos** [comment]
Ok I tried changing the language to English US but still error 666 on android, both are Xiaomi pocophone. Login does work from iPhone but the second bug is still present : 
If I try to update the task from obsidian, no popup is shown that there is an update from the plugin and then I cannot even add new tasks until I do a manual sync. I remember seeing in the android developper logs that TT blocks me after the failed update.
I don't really care about the login error because there is workaround by logging on desktop then syncing the vault to android.
I do hope we can understand the update bug from obsidian as I am using it quite often. It works flawlessly on desktop but I like updating my notes on mobile very often :) thanks for your help!

**Comment by coneos** [comment]
Here is more info, hope that will help.
Whenever I create a task I get this error on android but the task does get created on TT and the following ones as well :

plugin:tickticksync:7148 Error adding task: TypeError: Cannot read properties of undefined (reading 'createHash')
    at TaskParser.getLineHash (plugin:tickticksync:5723:26)
    at SyncMan.addTask (plugin:tickticksync:7144:52)
    at async SyncMan.lineContentNewTaskCheck (plugin:tickticksync:7121:5)
    at async eval (plugin:tickticksync:8526:9)
addTask @ plugin:tickticksync:7148
await in addTask
lineContentNewTaskCheck @ plugin:tickticksync:7121
eval @ plugin:tickticksync:8526
await in eval
e.tryTrigger @ app.js:1
e.trigger @ app.js:1
t.trigger @ app.js:1
t.onUpdate @ app.js:1
t.onUpdate @ app.js:1
(anonymous) @ app.js:1
e.update @ app.js:1
dispatchTransactions @ app.js:1
e.dispatch @ app.js:1
t.transaction @ app.js:1
t.selectSuggestion @ app.js:1
e.useSelectedItem @ app.js:1
e.onSuggestionClick @ app.js:1
s @ enhance.js:1
plugin:tickticksync:7149 The error occurred in file: TickTick/Tasks/Inbox.md


The bug starts when updating a task on obsidian and I get this error :
plugin:tickticksync:5723 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'createHash')
    at TaskParser.getLineHash (plugin:tickticksync:5723:26)
    at SyncMan.lineModifiedTaskCheck (plugin:tickticksync:7231:47)
    at TickTickSync.lineNumberCheck (plugin:tickticksync:8724:45)
    at async HTMLDocument.eval (plugin:tickticksync:8505:9)
	

Then I cannot even add tasks from obsidian and I see this :
plugin:tickticksync:8699 We're locked. Returning.

As I said the only way to get "unlocked" is running a manual sync.

**Comment by coneos** [comment]
Hi @thesamim 
I managed to make the task update work for mobile but the code is probably ugly as I have basic coding skills and chatgpt helped me =)
In Obsidian on Android, we apparently don't have access to Node.js APIs (like crypto.createHash) so I had to import the crypto-js library via CDN at the top of main.js :
`// Dynamically load the crypto-js CDN script at the top of the file
const script = document.createElement('script');
script.src = "https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.2.0/crypto-js.min.js";
script.onload = function() {
    console.log('crypto-js library loaded successfully!');
    // You can now use CryptoJS throughout the code
};
script.onerror = function() {
    console.error('Failed to load crypto-js library.');
};

// Append the script to the document
document.head.appendChild(script);
`

And then I modified the getLineHash like this : 
`getLineHash = function(resultLine) {
	console.log("getLineHash called with:", resultLine); // Debugging log to see the input
	if (!resultLine) {
		console.error("getLineHash: resultLine is undefined or null");
		return null;  // Exit early if resultLine is invalid
	}
	// Use crypto-js to generate the SHA256 hash instead of Node.js crypto
	const hash = CryptoJS.SHA256(resultLine).toString(CryptoJS.enc.Hex);
	console.log("getLineHash generated hash:", hash); // Debugging log to see the generated hash
	return hash;
};`

Now the tasks do get updated correctly on both mobile and desktop, hope that helps to make a new release fixing that issue, thanks again for this great plugin! :)

**Comment by thesamim** [comment]
@coneos : 
Thanks for the detailed error reports. 

Problem with Mobile login: was requesting an English response. When TickTick sends the non-english response the JSON is malformed. Removed the English response request. That fixed the login issue.

Thanks for the Crypto suggestion. I decided to go with crypto-hash as it's lighter weight and supported in both Electron and Capacitor. That took care of the hash issue.

Please take a look at the acknowledgement section of the Readme file in the next release. :)

**Comment by coneos** [comment]
I can confirm that both login and update issues are fixed in the new release and you also acknowledged me, you are amazing thank you!!!

**Comment by thesamim** [comment]
Thanks for your support! Happy New Year!
