### ISSUE TITLE
Login issue again

### ISSUE THREAD

**Issue by MandeepCodes** [thesamim/TickTickSync#39]
Even after logging in from settings TickTickSync is not working 
![image](https://github.com/thesamim/TickTickSync/assets/111353216/44850016-69ad-4fa3-9d5b-137c99a9cb26)

**Comment by MandeepCodes** [comment]
After some investigation. It is failing when Tray is enabled.
https://github.com/dragonwocky/obsidian-tray

**Comment by MandeepCodes** [comment]
@thesamim please check with this plugin installed and setup.

**Comment by thesamim** [comment]
Will investigate.

Meanwhile, if you could get me the console.log and the last 10 lines of TickTickSync's data.json from the following:
1. launch your plugin with/from tray plugin as  you would normally do
2. From TickTickSettings turn on Debug Mode.
3. From TickTickSettings Login.
4. Using your favorite method, start a Sync.

thanks.

**Comment by thesamim** [comment]
@MandeepCodes : Installed the plugin. Other than strange behaviour in the vault (eg: closes the whole vault on launching the Login window), it's not affecting the login functionality. I'm able to login and sync normally.

If you continue to see issues, I recommend you open an issue with https://github.com/dragonwocky/obsidian-tray
