### ISSUE TITLE
tasks created in ticktick doesn't sync to obsidian

### ISSUE THREAD

**Issue by rcetin** [thesamim/TickTickSync#44]
Hello, this is my configuration: 

![Selection_274](https://github.com/thesamim/TickTickSync/assets/11706483/ce3de045-6d59-4383-ba8d-cae997d53952)

If I understood correctly, any task created in ticktick in Work project will be synced to Obsidian. But it doesn't synced. 

Did I do something wrong? If it will sync, how extension decide which folder/file to sync (from ticktick to obsidian)?

Thanks, best regards.

**Comment by thesamim** [comment]
That should work just fine.

Could you please turn on debug mode and share your console log after a manual sync?

**Comment by thesamim** [comment]
@rcetin 
Hi, I think I reproduced your set up and everything is syncing for me.
![image](https://github.com/thesamim/TickTickSync/assets/5315625/ab4ea171-eedb-4ad7-b3e1-f0807036095a)

Please let me know if you continue to have the issue. A console log would be helpful.

Thanks.

**Comment by thesamim** [comment]
@rcetin : Could you please check if you a duplicated project(list)

In trying to replicate your issue, I saw this on TickTick:
![image](https://github.com/thesamim/TickTickSync/assets/5315625/774be2f1-90ab-4da8-a5a4-0e385a541b46)

I believe I may have caused this by clicking on the project(list) name in TickTick to copy it. For some reason, it created a new folder and didn't delete the old folder.

TickTickSync does not handle duplicate folder names at this time.... Which may be why you're not getting synchronization.

I've raised this with TickTick btw. 

I'm sure they'll fix it right away. <-- Sarcasm.

**Comment by rcetin** [comment]
My OS is Ubuntu btw, not sure if matters. This is console output and ss from TickTick.

![image](https://github.com/thesamim/TickTickSync/assets/11706483/43ff6bb2-b305-4df2-a7b0-f8880e96c8c4)
![image](https://github.com/thesamim/TickTickSync/assets/11706483/621d08be-d10f-4e58-a5aa-e551f21d0642)
![image](https://github.com/thesamim/TickTickSync/assets/11706483/a1243a21-21a3-4c26-8048-b6caed83b010)

**Comment by thesamim** [comment]
Ya, don't currently have a unix machine to test on. Sorry.

in  your  `<vault path>/.obsidian/plugins/tickticksync/data.json`, could please let me know the values for:
```
 "version": "",
  "baseURL": "",
  "defaultProjectId": "",
  "SyncTag": "",
  "SyncProject": "",
```
 I suspect, but don't know for sure that "SyncTag" is either not defined, or doesn't have a value. But I'm interested in what the other values might be.

I'm going to put some defensive code around that section though. It shouldn't cause an exception!

**Comment by rcetin** [comment]
```
  "version": "1.0.12",
  "baseURL": "ticktick.com",
  "token": "154BB8FE9144678395AD5701A23B190DEDB4C0190D615A5F6A6A7A3F467563223E46E3F71ABE90A78BF0812FB536114B9E8E944F19C34EFD006ABB58C699866460BDE4A16E962CA0822745DA42D34948FFFC0B0FC49F84AF5E125934C34B765082BEE463B1431075BC4DD36207DCA5A8FFFC0B0FC49F84AFC58CA89B0C522CFB124B38508E8ECC4274BF47F63B5F724D1AF5FA689B2E60B42536DE99079F68CEACE730BDF52673BB",
  "defaultProjectId": "6253035f1f07113431ed6d95",
  "SyncProject": "6253035f1f07113431ed6d95"
```

I don't have SyncTag :(

**Comment by thesamim** [comment]
Just for fun, could you please add 
```
 "SyncTag": "",
```
to the bottom of your file, restart Obsidian and try syncing again?

I'm working on that not happening, but want to make sure that's the only issue.....

**Comment by rcetin** [comment]
wow it worked!! It synced the tasks from ticktick to my daily note (22 Jan 2024). But how does it decide which file in Obsidian to sync ticktick tasks?

**Comment by thesamim** [comment]
Glad it worked!

But I'm surprised it synced to your daily note. Unless, somehow, your daily note ended being set to have 💼work as the default project. 

If you're ok with it: Could you email me your data.json file to thesamim [at] gmail [dot] com ? (obviously, please strip any sensitive information from tasks...)

**Comment by rcetin** [comment]
Not sure tbh. My that daily note had a heading2 named as "work". I tried to create another daily note for today and have the same heading and synced again. It is still syncing to 22 Jan 2024... 

Sure. I will send it, thanks!!

**Comment by martin-arg** [comment]
I'm having the same problem. I can create task in obsidian and sync to ticktick, but when i creat one task in ticktick, it won't sync to obsidian.

**Comment by thesamim** [comment]
@rcetin , @martin-arg : Could you please retest with 1.0.16?

**Comment by rcetin** [comment]
it looks working!

**Comment by thesamim** [comment]
> it looks working!

Glad to hear it. Thanks for your support.
