### ISSUE TITLE
Not support the Local Folder name by Chinese

### ISSUE THREAD

**Issue by Tback1** [thesamim/TickTickSync#45]
may be address this in the note
or deal it

**Comment by thesamim** [comment]
> may be address this in the note or deal it

Could you please paste a chinese folder name here so I can see what's going on?

**Comment by Tback1** [comment]
OK, it's like the follow one:
`\滴答清单`

**Comment by thesamim** [comment]
I think I found the problem. I will be releasing 1.0.14 shortly. If you could test there, I would appreciate it.

**Comment by thesamim** [comment]
@Tback1 : Could you please let me know if the bug fix fixed the problem for you?

Thanks.

**Comment by Tback1** [comment]
Yes this error is dispersed ,I think the fix fixed this issue.

but unfortunately, my test will not to say it's OK, the sync still can't susses,but i sure it's not because this issue
