### ISSUE TITLE
Creating task on Obsidian with backlink causes backlink to be deleted

### ISSUE THREAD

**Issue by rcetin** [thesamim/TickTickSync#48]
https://github.com/thesamim/TickTickSync/assets/11706483/fef14bbc-6343-404f-b0b6-7d1285a24cb7

Hey! When I created a task on Obsidian with a backlink to a file, that backlink is removed from task when ticktickSync modifies it to create a task on TickTick. See the video.

When the backlink is removed from Obsidian , I see on TickTick app name looks good like I created with backlink ([[xxx]]). However, when I modify the task from Obsidian, that backlink also removed from TickTick app and only the letters were there in TickTick app as well.

**Comment by thesamim** [comment]
Video didn't upload or is corrupted.

But I can reproduce the problem. Will work on it.
