### ISSUE TITLE
Weird %% artifacts in tasks

### ISSUE THREAD

**Issue by Suyashtnt** [thesamim/TickTickSync#52]
rt.
![image](https://github.com/thesamim/TickTickSync/assets/45307955/7066ff29-2c63-4d9c-a7cf-2cb56691c567)
(This plugin pulls from tasks created. It's also visible in note, however due to my theme I can mostly ignore them)
It makes it much more annoying to read in custom views.

**Comment by thesamim** [comment]
What's between the '%' charters is the TickTick ID for the task. the '%' character is mardown for "Comment" and should not be visible. At least in Reading and Live Preview mode. 

Tell me more about custom views. 

Also, what theme are you using?

**Comment by Suyashtnt** [comment]
> What's between the '%' charters is the TickTick ID for the task. the '%' character is mardown for "Comment" and should not be visible. At least in Reading and Live Preview mode.
> 
> Tell me more about custom views.
> 
> Also, what theme are you using?

Theme is border. The %% are visible in live preview mode. I don't think hiding the ticktick ID is nessesary personally.

**Comment by Suyashtnt** [comment]
The custom view is from Tasks Calendar Wrapper. Not exactly sure how it works

**Comment by thesamim** [comment]
Will investigate.

**Comment by thesamim** [comment]
@Suyashtnt Problem is in the Task Calendar Wraper. When it generates it's sidebar view, it parses the tasks. It does not account for comments in %%...%%

Please open an issue here: https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/issues
