### ISSUE TITLE
Plugin can't read/detect tasks which are scheduled rather than having a start date

### ISSUE THREAD

**Issue by Suyashtnt** [thesamim/TickTickSync#53]
rt. TickTick doesn't show schedule dates for tasks that are scheduled with an hour glass/scheduled field
![image](https://github.com/thesamim/TickTickSync/assets/45307955/1aab5392-919c-44bc-8ee6-a6f34841c1a0)

**Comment by thesamim** [comment]
That's right. TickTickSync only looks at Due Date. TickTick only tracks Due Date and Start Date. Where would like "Schedule Date"?

**Comment by Suyashtnt** [comment]
> That's right. TickTickSync only looks at Due Date. TickTick only tracks Due Date and Start Date. Where would like "Schedule Date"?

If there's a scheduled date, prefer it over the due date. Since semantically, the scheduled date is when you want to do the task while the due date is the latest you can do it

**Comment by thesamim** [comment]
Will make that an option in one of the upcoming releases.
