### ISSUE TITLE
Obsidian quits after account authentication when quitting ticktick pop up windown

### ISSUE THREAD

**Issue by piloadami** [thesamim/TickTickSync#56]
I'm trying to create a task from within ticktick using the #. 

In obsidian I'm getting an error that i need to login. I press login it gives me pop up window. I log in and quit the window Obsidian quits and does not maintains the log in.

**Comment by thesamim** [comment]
Need some information please:

- what platform are you on?
- can you log in ok from the web?
- are there any error messages?
- if there are no errors messages, please share your console log.

**Comment by thesamim** [comment]
Please try again with 1.0.16 and let me know what happens.

**Comment by thesamim** [comment]
@piloadami : Is this still happening?
