### ISSUE TITLE
Done dates are not being inserted

### ISSUE THREAD

**Issue by Suyashtnt** [thesamim/TickTickSync#64]
When marking a task as done in ticktick, the task's done date is not inserted into obsidian. This makes the todo plugin and it's API think that the task was not completed yet, leading to issues with other plugins and ```task block

![image](https://github.com/thesamim/TickTickSync/assets/45307955/49f9cc28-eeb8-4822-92e7-aa5fd3c249be)
While this is _done_, it shows up as not being done as it doesn't have a done date attached.
![image](https://github.com/thesamim/TickTickSync/assets/45307955/3ef3babe-7f41-4a1a-9d27-a0dc7264b991)

**Comment by thesamim** [comment]
@Suyashtnt : are you using the Tasks plugin? 

If you are: done dates are inserted by Tasks and not touched by TickTickSync. If you are seeing different behavior, please let me know.

If you are not: I strongly recommend using the Tasks plugin because all the date logic, query logic etc is supported by the Tasks plugin....

**Comment by Suyashtnt** [comment]
> @Suyashtnt : are you using the Tasks plugin?
> 
> If you are: done dates are inserted by Tasks and not touched by TickTickSync. If you are seeing different behavior, please let me know.
> 
> If you are not: I strongly recommend using the Tasks plugin because all the date logic, query logic etc is supported by the Tasks plugin....
> 
> Also: that plugin should be determining done status based on the task checkbox status. Could you please give me a link to that plugin so I can test on my side?

I am using the tasks plugin. The menu I showed is the tasks plugin ```tasks block. The tasks plugin itself doesn't determine if something is done based on if its checked or not, but rather based on the presence of the done field

**Comment by thesamim** [comment]
Thanks for pointing out the issue. Should be fixed now.

**Comment by Suyashtnt** [comment]
new issue: the plugin moves it into a place where the task plugin no longer takes is into consideration. It should be moved to the end of the line rather than before link

```md
- [X] English comprehension          ✅ 2024-03-07  [link](https://ticktick.com/webapp/#p/inbox123040542/tasks/65e70b795b708c8a7308b71c) #ticktick %%[ticktick_id:: 65e70b795b708c8a7308b71c]%% 📅 2024-03-07
```

![image](https://github.com/thesamim/TickTickSync/assets/45307955/2acf0e7f-43ec-4604-8ed2-c412cfcd45ee)
(the tasks plugin \`\`\`task block is showing that I have not completed it yet)

**Comment by thesamim** [comment]
Please update to 1.0.18. Please let me know results.

**Comment by Suyashtnt** [comment]
It seemingly removed the done tag rather than move it.
![image](https://github.com/thesamim/TickTickSync/assets/45307955/1454121a-0354-4b5b-ada3-745de9fff85e)

```md
- [X] Business cycle test #business [link](https://ticktick.com/webapp/#p/inbox123040542/tasks/65ba9f155f2e6656d28f8b8a) #ticktick %%[ticktick_id:: 65ba9f155f2e6656d28f8b8a]%% 📅 2024-02-29
```

**Comment by Suyashtnt** [comment]
sorry that I completely forgot about this issue. I'll test it when I have a chance.

**Comment by thesamim** [comment]
I did find a couple of issues that I believe I fixed. Looking forward to hearing your results.

**Comment by Suyashtnt** [comment]
> I did find a couple of issues that I believe I fixed. Looking forward to hearing your results.

seems to be working perfectly now!

**Comment by thesamim** [comment]
Thanks for the update.
