### ISSUE TITLE
Allow custom tags to be synced with Obsidian

### ISSUE THREAD

**Issue by khushnoodasif** [thesamim/TickTickSync#7]
I think by default all ticktick tasks are tagged with #ticktick and are synced to Obsidian. Would be better to add an option not sync all but only with certain tag e.g. #obsidian, #backlog or any custom tag, this way it can be managed properly. You could still keep all lists as markdown but an option for markdown per task/list would be better.

**Comment by thesamim** [comment]
> [...] You could still keep all lists as markdown but an option for markdown per task/list would be better.
Please expand on the above. If you could, please provide an example.

**Comment by khushnoodasif** [comment]
For a certain tag e.g. #obsidian you could have a option that defines which tasks/notes with that tag to be synced into Obsidian. This could either do as before and showcase as markdown for the list of the task or you could create a markdown for each task/note. Either option would work but since in TickTick you can only tag on each task or note the second option seems better to me.


In TickTickSync Settings:
Choose tag: obsidian (could actually have list of tags here)

This would generate markdown or tasks with that tag.

**Comment by thesamim** [comment]
@khushnoodasif , I want to make sure I understand the request. Please take a look at the following. If it's not what you have in mind, please let me know.
# Current
## From Obsidian
If a task has the #ticktick tag, it is added to TickTick
	If it has a tag that corresponds to a TickTick list, or if it is added in a file which is associated with a default list, it is added to that list, 
		else it is added to the Inbox
If a task has the #ticktick tag, and TickTick ID, and is updated, it is updated to TickTick
If a task has the #ticktick tag, and TickTick ID, and is deleted, it is deleted from TickTick
## From TickTick
ALL Tasks are synced
If a task is added, it is added to a file
	If the task is in a list, and that list is the default list for a  file, it is added to that file.
		else it is added to the file associated with the default project
If a task is updated, it is updated in the corresponding file in Obsidian
If a task is deleted, it is deleted from the corresponding file in Obsidian

# Proposed
## From Obsidian
If a task has the #ticktick tag, it is added to TickTick
	If it has a tag that corresponds to a TickTick list, or if it is added in a file which is associated with a default list, it is added to that list, 
		else it is added to the Inbox
If a task has the #ticktick tag, and TickTick ID, and is updated, it is updated to TickTick
If a task has the #ticktick tag, and TickTick ID, and is deleted, it is deleted from TickTick
## From TickTick
New Preference: Sync ALL tasks, or Sync Tasks with a specific Tag
If ALL Tasks is selected, behavior is as in current.
If specific tag is selected.
If a tagged task is added, it is added to a file
	If the task is in a list, and that list is the default list for a  file, it is added to that file.
		else it is added to the file associated with the default project
If a tagged task is updated, it is updated in the corresponding file in Obsidian
If a tagged task is deleted, it is deleted from the corresponding file in Obsidian

**Comment by khushnoodasif** [comment]
Yes what you have mentioned in the proposed section seems to align with what I am looking for. Looking forward to it!

**Comment by kmaustral** [comment]
I second this. I found that on first sync all my TickTick tasks were deleted and I can't retrieve them.

**Comment by gradypark86** [comment]
I also agree with this suggestion. Once all tasks are synchronized, their titles and tags will be changed, affecting tasks not related to obsidian. 
For me, it's fine to sync with a specific tag or a specific list in ticktick.

**Comment by MartinP7r** [comment]
side note: Especially in relation to the Tasks plugin (which is recommended in your readme). Many people most likely use the option to only pick up tasks that have the `#task` tag for Tasks plugin, so having the option to set the ticktick tag to the same (e.g. `#task` instead of `#ticktick`) would be helpful.

**Comment by thesamim** [comment]
> only pick up tasks that have the `#task` tag for Tasks plugin

Good suggestion. I will investigate. My, minor, concern: Tasks does special processing with the "Global tag". I want to make sure TickTickSync doesn't interfere with that and vise versa....
