### ISSUE TITLE
"Hide comments" in styles.css breaks comments in other code blocks

### ISSUE THREAD

**Issue by LemurTech** [thesamim/TickTickSync#71]
The first line of css in the current version is this:

.cm-line:not(:hover):not(.cm-active) span.cm-comment {
    display: none;
}

It has the unintended consequence of hiding comment blocks in ALL code blocks that are of the "cm-comment" class. It should probably be something like:

.cm-line:not(:hover):not(.cm-active) span.cm-comment:not(.cm-hmd-codeblock) {
    display: none;
}

Thanks for this great plugin!

**Comment by thesamim** [comment]
@LemurTech : Thanks for raising this.

Will be in next release.

Q: if I'm reading this right, this only prevents the hiding of comments inside code blocks. Is that right? Is that the desired outcome?

You're welcome! Thanks for using it.

**Comment by LemurTech** [comment]
> Q: if I'm reading this right, this only prevents the hiding of comments inside code blocks. Is that right? Is that the desired outcome?

Yes, that's the intention. It's working for me so far. All my comments in PowerShell code blocks were getting hidden except when hovered over.

**Comment by thesamim** [comment]
@LemurTech : thanks for the confirmation.
