### ISSUE TITLE
Duplicate Tasks

### ISSUE THREAD

**Issue by LemurTech** [thesamim/TickTickSync#73]
I'm having persistent problems with duplicated tasks on the master "project" list in Obsidian. These are not duplicated in TickTick, as their ID appears to be exactly the same. When I remove them manually from the list, they seem to just reappear. The Tasks plugin does not seem to have any 'dedupe' capabilities. Note that the lack of %% comment delimiters in the screenshot is due to css removing them.

![image](https://github.com/thesamim/TickTickSync/assets/3136325/042c4d90-3299-49c5-bba5-11957471440f)

**Comment by thesamim** [comment]
Thanks for raising this.

I actually started seeing that on my set up and am dealing with the dedupe logic as we speak. Will be in next release.

**Comment by LemurTech** [comment]
I'm very excited to see this fix! That said, I don't see any changes retroactively applied. Should I just manually remove the duplicates? Thank you!

**Comment by thesamim** [comment]
Yes please.

Automatic removal would have been too risky to implement.

BUT: if you see duplicates again, PLEASE let me know ASAP.

**Comment by LemurTech** [comment]
Understood and will do. Cheers!

**Comment by LemurTech** [comment]
I'm still seeing duplicates. But now it occurs to me that the reason may be because of Obsidian Sync. I'm going to try excluding the TickTick tasks default folder.

**Comment by thesamim** [comment]
Please keep me posted.

**Comment by LemurTech** [comment]
If I were to delete all tasks from the default project file, would they be downloaded again from TickTick on next sync? Or would the sync try to delete them from TickTick?

**Comment by thesamim** [comment]
> If I were to delete all tasks from the default project file, would they be downloaded again from TickTick on next sync? Or would the sync try to delete them from TickTick?

They would be deleted from TickTick.

If you want to start over, and are feeling pretty brave :) :
1. Close Obsidian everywhere.
2. Back up the default project file.
3. Back up `<your vault root>\.obsidian\plugins\tickticksync\data.json`
4. edit `<your vault root>\.obsidian\plugins\tickticksync\data.json`
5. Find the `"tasks":` entry and make it `"tasks": []` (ie: delete all the task entries)
6. Find the `"fileMetadata":` entry and make it `"fileMetadata": {}` (ie: delete all the fileMetaData entries)
7. Verify that the JSON parses correctly after changes (I suggest going to https://jsonlint.com and pasting the content there to validate it.)
8. delete the default project file
9. Restart Obsidian in one place
10. Sync again.

That should reset your default project file to look like your TickTick...

**Comment by LemurTech** [comment]
That actually worked very well! Thank you for the clear process!

**Comment by thesamim** [comment]
Welcome.

Please keep me posted...
