### ISSUE TITLE
Blank spaces in tasks

### ISSUE THREAD

**Issue by LemurTech** [thesamim/TickTickSync#74]
Can anything be done about all the blank spaces being created in the tasks? It's visually very distracting. Thank you!

![image](https://github.com/thesamim/TickTickSync/assets/3136325/dfa69821-eb48-4ede-ac3c-5cfc2f879c86)

**Comment by thesamim** [comment]
I believe the next release will do a better job of handling the date manipulation. Still testing. Will keep you posted.
