### ISSUE TITLE
Due dates in the wrong format

### ISSUE THREAD

**Issue by Suyashtnt** [thesamim/TickTickSync#76]
It seems that tickticksync automatically converts the due dates to `YYYY-DD-MM`, when it should be `YYYY-MM-DD`.

![image](https://github.com/thesamim/TickTickSync/assets/45307955/974c1472-569a-41e2-be69-de22fcf9ca7b)
^ those above tasks are due for March 5th, but it shows as May 3rd. Manually changing it to YYYY-MM-DD works, but it converts it back automatically.

**Comment by thesamim** [comment]
@Suyashtnt : TickTickSync only generates YYYY-MM-DD dates from the code. 

The two dates I see in your screen shot that TickTickSync generates are: 
2024-03-04 
2024-03-01 

How are the heading dates (Friday, May, 3 and Saturday, Nov, 2) generated? If they come from a DataView or Tasks query: is it possible you have set a different date/time pattern than the default?

What other plugins do you have installed?

**Comment by Suyashtnt** [comment]
> @Suyashtnt : TickTickSync only generates YYYY-MM-DD dates from the code.
> 
> The two dates I see in your screen shot that TickTickSync generates are: 2024-03-04 2024-03-01
> 
> How are the heading dates (Friday, May, 3 and Saturday, Nov, 2) generated? If they come from a DataView or Tasks query: is it possible you have set a different date/time pattern than the default?
> 
> What other plugins do you have installed?

those 2 dates are actually just file names. Those heading dates are generated through the tasks plugin directly iirc (the plugin itself is task-calendar-wrapper). The task plugin also shows them due in a few months and in the files themselves the dates are formatted at YYYY-DD-MM.

**Comment by Suyashtnt** [comment]
![image](https://github.com/thesamim/TickTickSync/assets/45307955/89b7c236-b766-44b1-abae-e5aab00b2d84)
example of the date format being in a note (It's meant to be for the 9th of march)

**Comment by thesamim** [comment]
Please attach the .md file here. I think the issue is with task-calendar-wrapper

**Comment by Suyashtnt** [comment]
> Please attach the .md file here. I think the issue is with task-calendar-wrapper

task-calendar-wrapper does no write operations unless you create a new task through it (which I've never done in any of these cases)

I can't attach the whole file but the snippet itself is
```md
# Programming
## Website
- [ ] Rework website theming   #personal [link](redacted) #ticktick %%[ticktick_id:: 65bfb867d49520110ec8b491]%% 📅 2024-09-03 
	- [ ] MasterCSS rewrite %%65e6f251525062d866781693%% 
	- [ ] Light theme for kleur %%65bfb86bd49520110ec8b493%% 
	- [ ] Switch to motion one for animations %%65e6f251525062d866781694%% 
	- [ ] Add some nicer transitions and animations (keep them useful though. Don't go overboard future me) %%65e6f251525062d866781695%% 
	- [ ] XML theme/template thing for atom feed %%65e6f251525062d866781696%% 
	- [ ] Webmention support %%65e6f251525062d866781697%%
```

**Comment by thesamim** [comment]
Could you please:
1. create a test task, without the ticktick tag with a due date.
2. create a test task, with the ticktick tag with a due date

and send me both.

Thanks.

**Comment by Suyashtnt** [comment]
new info: this seemingly only breaks on my desktop running linux. There could be some other things going on

**Comment by Suyashtnt** [comment]
... and now fixed itself on linux. What the hell. I'm closing this I guess?

**Comment by thesamim** [comment]
@Suyashtnt : Thanks for the update. If it happens again, please do not hesitate to raise it again.
