### ISSUE TITLE
Open modal causes plugin to think all tasks have been deleted

### ISSUE THREAD

**Issue by LemurTech** [thesamim/TickTickSync#77]
I've experienced this multiple times now. When a modal dialogue of some kind is open (for example, the Quick Switch or Command Palette), and the plugin attempts a sync, it will think that all tasks on the current page have been deleted and will prompt for the removal of these tasks from TickTick. This can really cause problems, as I've had it that the dialogue for deletion comes up when I'm typing into the modal and inadvertently hit enter--thereby deleting a bunch of tasks that I did not intend to delete.

![image](https://github.com/thesamim/TickTickSync/assets/3136325/ed376a6c-af43-49c1-85da-9ff90b387e3e)

**Comment by thesamim** [comment]
@LemurTech : There are actually a number of situations that cause that to happen. I've decided it's a false positive and removed that code. If the tasks ARE actually deleted, they will get deleted on the next full Sync.

Please test on version 1.0.18 which should be ready later today.
