### ISSUE TITLE
Date error

### ISSUE THREAD

**Issue by 4ependoZzz** [thesamim/TickTickSync#79]
![Screenshot_20240311_231905_Obsidian](https://github.com/thesamim/TickTickSync/assets/163017470/5aacb53b-577a-46f6-9325-b0c46f317a75)
Hi, every time when I input due date in obsidian task or task in ticktick this date update after sync with "undefined" and I can not use tasks in obsidian and tick tick

**Comment by 4ependoZzz** [comment]
I know that the date format in TickTick is YYYY-MM-DD. I found confirmation of this here:
[TickTick Developer](https://developer.ticktick.com/docs#/openapi)

Instead of "undefined," I expected to see 📅 2024-03-17.

Also:
1. I made an experiment on a new storage without any additional plugins. I installed only Tasks and TickTickSync plugins.
2. Accordingly, no plugins change the date format.
3.1. In Obsidian, I enter the date through the task menu. Afterward, it ends up at the end of the task in normal form. Then, during synchronization, it is replaced with undefined-DD.MM.YYYY-undefined. After that during synchronization back from TickTick, the date is placed before the tag. In TickTick, the date is not set, and the entry undefined-date-undefined goes into the task description.
3.2. In TickTick, I set the date in the standard way. It also ends up at the end of the task in Obsidian in the format undef-DD.MM.YYYY-undef during synchronization, and after that, it is moved into the body of the task. In TickTick, the date is cleared at this point.

**Comment by 4ependoZzz** [comment]
It might also be useful for investigating my issue.
I also tried installing the Ultimate Todoist Sync plugin in another obsidian vault. With it, this problem did not occur. I think the issue is not with the date format on the Obsidian side.

**Comment by thesamim** [comment]
What platform is this happening in?


>
>        3.1. In Obsidian, I enter the date through the task menu. Afterward, it ends up at the end of the task in normal form. 
>
Are you putting in a scheduled date or a due date?

Please do this: 
1. Please enter a task using the same method, but do NOT add the TickTick tag. copy the line from the .md file and paste it here.
2. using your favorite method (Ctrl-Shift-I in Windows. Don't know what it is in other platforms) go to the debug console.
3. In the console type in `console.log(Intl.DateTimeFormat().resolvedOptions().timeZone)` and let me know what you see. 
![image](https://github.com/thesamim/TickTickSync/assets/5315625/bf703e7b-e845-4d0a-9275-c5caecad2ad0) is what I see...

4. In Ticktick, what time zone do you have?

It looks like we're losing year and day in the time zone conversion (the two undefineds.)

**Comment by 4ependoZzz** [comment]
The setup is the same on both platforms (win, android)
I put in due date
1. Example from obsidian android (same on the win):
- [ ] test task 📅 2024-03-17
2,3 Asia/Irkutsk
4. [image](https://github.com/thesamim/TickTickSync/assets/163017470/87f76c2a-a98a-4779-8ad2-10cf99edaf49)

**Comment by thesamim** [comment]
I'm sorry, I'm not able to reproduce this. I have set my timezone the same as yours on both Windows and Android. All working as designed. 
![image](https://github.com/thesamim/TickTickSync/assets/5315625/b46b4b1d-89c5-4887-a0a8-e60d5dd97b12)

I have not tested this with any language other than English. Is it possible that we are running into a language difference problem?

Could you please 

1. back up your main.js file in `<your vault root>\.obsidian\plugins\tickticksync`
2. replace it with the main.js here in this zip file: [main.zip](https://github.com/thesamim/TickTickSync/files/14575935/main.zip)
4. filter console with "@@@"
5. let me know what you see.

**Comment by 4ependoZzz** [comment]
Sorry, I can't download this file (main.zip)
Error 54113 the same in this discussion [error 54113](https://github.com/orgs/community/discussions/112288)

**Comment by thesamim** [comment]
Let's try this: https://github.com/thesamim/TickTickSync/blob/65-enable-plugin-on-android-mobile/dist/TickTickSyn-1.0.18-Test.zip and click on download. 
![image](https://github.com/thesamim/TickTickSync/assets/5315625/4144b5b6-4ea9-4ee1-b5e6-624b79254063)

**Comment by 4ependoZzz** [comment]
I got it))
![2024-03-13 163655](https://github.com/thesamim/TickTickSync/assets/163017470/22969742-80b0-40dd-bcd2-e8603b4b68c6)
yellow hilight looks provocative

**Comment by thesamim** [comment]
Thanks! That was helpful.

I believe I found the issue: date.toLocaleString is returning date in your locale format, but I was not accounting for the difference in formats. I have made a change to always get the local time in the format the code is expecting. 

If you could check two things please: 
1. That we don't see `undefined-17.03.2024-undefined` any longer
2. That the date for the task is accurate per your time zone

Please download: https://github.com/thesamim/TickTickSync/blob/65-enable-plugin-on-android-mobile/dist/TickTickSyn-1.0.18-Test.zip again and let me know if that did, indeed, fix the problem.

**Comment by 4ependoZzz** [comment]
Hi, the archive is corrupt. Upload one more please

**Comment by thesamim** [comment]
@4ependoZzz : it downloaded fine for me. But anyway: I deleted it and added back to repository. Please try again.

**Comment by 4ependoZzz** [comment]
@thesamim 
my browser has lost its head)) I tested the latest version
Everything is fine!!!)) thank you very much for the quick solution to the issue!!!

**Comment by thesamim** [comment]
You're welcome. Thanks for your patience and help.

I will put out a new release in the couple of days.
