### ISSUE TITLE
Syncing completed tasks

### ISSUE THREAD

**Issue by kilabyte** [thesamim/TickTickSync#90]
**Describe the feature**
I want to sync everything, so I leave both project and tag blank. This syncs beautifully; however, it is syncing even completed tasks. Can we have an option to 'skip' completed tasks? OR Can you make it so that completed tasks don't show up in the 'Tasks' plugin? Even though they are completed the 'Tasks' plugin picks them up as not-completed.

**Desktop (please complete the following information):**
 - OS: Mac 14.4

**Comment by thesamim** [comment]
Which version of TickTickSync are you using? as of 1.0.20 the incoming completed tasks should have a completion date appended at the end of the line. Which should make Tasks see them as completed.

If this is not happening, please let me know the details of tasks that are NOT getting their completion dates appended. As in: Do you a see a completion date on TickTick, do you see a completion date anywhere on the Task line? Is there anything special about the task's content?

Filtering by task status could add some horrendous complexity. I'd be willing to do it, but would have to think through ALL the side effects. (And will need your help in working out the use cases...)

**Comment by kilabyte** [comment]
yes correct, 1.0.20. The tasks come in and are marked completed but it seems that the 'Tasks' plugin still views them as uncompleted. I would of just assumed you can just set the flag of != 'completed' based on a flag in the settings of the plugin. If this is a huge thing to work out then we can close this and no need to worry. Thanks for the response!

**Comment by thesamim** [comment]
Please upgrade to 1.0.22 and let me know what happens. (It shouldn't make a difference, but just for completeness..)

Please paste one of the completed tasks in here that Tasks is not seeing as completed. (editing out any personal or private information of course). I've spent an awful lot of time on making sure Tasks gets it right. I'd hate to think I missed a use case. :) 

Filtering on the task status is easy enough. But:

- What do we do if a task is completed in Ticktick, but we are filtering completed tasks? 
- What do we do if a task is completed in Obsidian, then re-opened in TickTick?
- ...

Not trying to be smart-ass, but we have to take all the possibilities into account....

**Comment by alno** [comment]
I've also noticed what synced completed tasks aren't handled like completed by Tasks plugin. 

I think it's because TickTickSync writes their status as `[X]` (uppercase), while Tasks expects completed task to have `[x]` (lowercase).

I've added custom Tasks status as a workaround, but I think it may be better if TickTickSync writes completed status in lowercase.

**Comment by thesamim** [comment]
Tasks only looks at the presence or absence of a completed date. It does not, last time I looked, even looked at the check box status. If you are seeing different behavior, please paste a completed task giving you problems here.

**Comment by alno** [comment]
In my experience Tasks doesn't care about presence of completed date at all =)

I just created a clean setup to test Tasks behavior:
* Created new vault
* Installed Tasks plugin
* Created a file with 5 tasks - one uncompleted and 4 for all combinations of lowercase/uppercase and date present/not present
* Added a query `done`

You may see results in the screenshot:
![image](https://github.com/thesamim/TickTickSync/assets/30774/ec0089cf-687c-4132-ad4c-68b0c7c9fa00)

There is a source, if you want to try it by yourself:
[TestTasks.md](https://github.com/thesamim/TickTickSync/files/14858118/TestTasks.md)

Also, you may find in Tasks documentation what it's lowercase `x` which is used as core status, not `X`: https://publish.obsidian.md/tasks/Getting+Started/Statuses#More+about+Statuses
