### ISSUE TITLE
Better Date/Time handling

### ISSUE THREAD

**Issue by LemurTech** [thesamim/TickTickSync#97]
Hi @thesamim! As we know, scheduled times are not supported by the Tasks plugin. When TickTickSync pulls in such time-scheduled tasks from TickTick, it preserves the scheduled time.

Unfortunately, this means the task date information will no longer be recognized by the Tasks plugin, which parses the line in reverse, and as soon as it fails to parse an emoji signifier, it considers the remainder of the line to be the 'description' field:

![image](https://github.com/thesamim/TickTickSync/assets/3136325/fc583290-9f45-4642-8fda-1d00b3a82e20)

What's the level of effort for TickTickSync to parse out the time info when it imports to Obsidian, but then not disturb any existing time info on TickTick when it updates an existing task in TickTick (say if the description is edited)?

**Comment by thesamim** [comment]
The level of effort would be huge. Will think about:

1. Making a setting option to just ignore times altogether
2. OR storing time somewhere else

**Comment by LemurTech** [comment]
Understood. Thanks for looking into it!

**Comment by blahnika** [comment]
Had the same problem, and would be nice to have an option to remove the time, or put it somewhere else.

**Comment by NaturallyAsh** [comment]
@thesamim Is this still planned?

**Comment by thesamim** [comment]
> @thesamim Is this still planned?

Yes it is. It's top of the Project Plan. Working on it right now.

**Comment by Jastmaskerrr** [comment]
@thesamim I think it is possible to put the scheduled times at the beginning of the task, for example `- [ ] 22:05 This is a demo 📅 2024-11-26`, and to avoid not recognizing it, you can also use `sort by description` in the tasks code block, in chronological order

**Comment by thesamim** [comment]
@LemurTech 
@NaturallyAsh 
@blahnika 
@Jastmaskerrr 
@zarb1

You have all commented on this or a similar issue regarding the handling of time in TickTickSync. I have made the changes to handle time. It's a pretty radical change. I have tested to the best of my ability, but I'm pretty sure there are use cases I've missed.

I would appreciate your help in testing this before I release it.

Words of caution:
1. While tested, I'm not absolutely positive I haven't missed something major. So I recommend taking backups and safeguarding your projects.
2. The time representation is arbitrary. If there's a due date only, or a start/scheduled date only, the time will be converted to [HH:MM] at the beginning of the line. If there are both due date and start date the time will be converted to [HH:MM - HH:MM] at the beginning of the line. So if you enter: 
`some task 📅 2024-11-29 10:00 🛫 2023-11-28 08:00` 
when TickTickSync uploads it you will then see: 
`[08:00 - 10:00]  some task  [link] #ticktick  %%[ticktick_id]%% 📅 2024-11-29 🛫 2023-11-28`

Would really appreciate any testing you can do and any feedback you can provide.

[TickTickSync - Test Only - 1.0.40.zip](https://github.com/user-attachments/files/17951332/TickTickSync.-.Test.Only.-.1.0.40.zip)

I'm going to assume you know what to do with the Zip file. If you don't please let me know.

Thanks in advance!

**Comment by NaturallyAsh** [comment]
@thesamim Tested your changes, and it works perfectly! I genuinely appreciate you and your great work on this plugin.

**Comment by thesamim** [comment]
Thanks @NaturallyAsh
